### ISSUE TITLE
Proposal: Add an option to hide sensitive data from logs

### ISSUE THREAD

**Issue by codeadict** [vernemq/vernemq#1017]
Under the scope of GDPR and any future privacy law, I think it would be beneficial for VerneMQ to support a boolean configuration option named `log.scrub_sensitive_data`, defaulting to `false` for backward compatibility. This will ideally be implemented in `vernemq_dev` and reused in the core applications to hide stuff like IP addresses, usernames, allowing plugin developers to also use it for their log messages.

**Comment by larshesel** [comment]
I like this idea a lot! I'll assign this to the 1.7.0 milestone for now.

**Comment by ioolkos** [comment]
Just adding a reference: https://github.com/rabbitmq/credentials-obfuscation

**Comment by ioolkos** [comment]
Time to address this.

This is about 2 things:
1. Protecting FSM session state (so that stack traces do not expose password). Credentials_obfuscation is obviously a candidate library.
2. Sanitize MQTT Frames before logging in all places (main candidate here is the CONNECT frame)

I consider the question of MQTT payload in a logged stack trace to be a bit different. It can be encrypted by end users.
First thing is a concept of what we actually want to do, and how fine-grained obfuscation options should be.

cc @mths1

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
IMO what should be hidden (as a minimal baseline) is

- MQTT passwords
- Credentials (Diversity DB, API Keys...)

I played with the credentials-obfuscation library and it worked well (for file-based auth). We would need to make it available in diversity as well if we want to have the password decoded only where necessary. It might also be an option to strip sensitive data in a logging framework (time to switch away from lager :-))

Some other ideas are here:
https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/sensitive_data.html

**Comment by ioolkos** [comment]
@mths1 yes to all of the above :)
Including getting away from lager... a bit of an effort, though.
The `format_status` callback for OTP behaviours might be a low-hanging way to control leaking of process status.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
