### ISSUE TITLE
VerneMQ crash after some seconds

### ISSUE THREAD

**Issue by davideicardi** [vernemq/vernemq#1030]
### Environment

- VerneMQ Version: 1.4.1
- OS: RedHat 7
- Cluster size/standalone: 2

### Description

We have 2 VM with the same configuration. On one of this when we start vernemq after some time we get the following error and VerneMQ crash:

```
vernemq console
```

```
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,plumtree,{{error,{shutdown,{failed_to_start_child,plumtree_metadata_leveldb_instance_sup,{shutdown,{failed_to_start_child,plmtrlvld_0,{db_open,\"IO error: lock /var/lib/vernemq/meta/meta/0/LOCK: Resource temporarily unavailable\"}}}}}},{plumtree_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,plumtree,{{error,{shutdown,{failed_to_start_child,plumtree_metadata_leveldb_instance_sup,{shutdown,{failed_to_start_child,plm
```

Any idea? The other VM seems to work correctly. They are not yet clusterized due to the above problems.

vernemq.conf is the default one expect for:
```
listener.tcp.external = 172.31.21.7:1883
listener.vmq.clustering = 172.31.21.7:44053
nodename = VerneMQWaspIoTPilot@172.31.21.7 # .8 on the second VM
distributed_cookie = vmq-waspiot-pilot
```

thanks

**Comment by ioolkos** [comment]
Hi @davideicardi thanks... the problem here is the LevelDB metadata DB. VerneMQ seems not able to access this. 
Do you have another Verne node running there? other permissions/disk troubles?
Can you afford deleting the whole metadata folder and restart Verne? (only do this if you can afford to loose state). Verne will then generate fresh data directories.

**Comment by davideicardi** [comment]
Thanks @ioolkos . Deleted the `/var/lib/vernemq` folder seems to have resolved. Maybe it was corrupted for some reason. Thanks!

**Comment by ioolkos** [comment]
@arntdr just a quick note on the netsplit question: any node that's down creates a netsplit. You seem to have configured your cluster for full consistency (making the cluster act like a single endpoint) instead of availability. (have a look at all those  `allow_` configs in the `vernemq.conf` file).
