### ISSUE TITLE
Configurabe keepalive value

### ISSUE THREAD

**Issue by ermalguni** [vernemq/vernemq#1089]
Hi,

In mosquitto there is the possibility to configure the keepalive timeout. From what I saw, vernemq is defaulting to 60 seconds. Is there a way to configure it to a custom value?

**Comment by larshesel** [comment]
The keepalive value is set by the client in the CONNECT frame when the client connects. See the documentation of the client library you're using.

I hope this helps.

**Comment by wlisac** [comment]
It might be nice to allow VMQ to be configured with a max keep alive value for MQTT 5.0 clients, similar to mosquitto broker.

I don't personally have a current use case for this, but I noticed it doesn't appear to be configurable in VMQ while testing my MQTT client.

>max_keepalive value
For MQTT v5 clients, it is possible to have the server send a "server keepalive" value that will override the keepalive value set by the client. This is intended to be used as a mechanism to say that the server will disconnect the client earlier than it anticipated, and that the client should use the new keepalive value. The max_keepalive option allows you to specify that clients may only connect with keepalive less than or equal to this value, otherwise they will be sent a server keepalive telling them to use max_keepalive. This only applies to MQTT v5 clients. The maximum value allowable, and default value, is 65535. Do not set below 10 seconds.

https://mosquitto.org/man/mosquitto-conf-5.html

**Comment by larshesel** [comment]
It isn't directly configurable, but it is possible to control via a plugin implementing the `auth_on_register_m5` hook.

That said it might be worth it to have a global value as well. Could you open up an issue requesting the feature so we can discuss it there?
