### ISSUE TITLE
Add properties to MQTT v3/v4 `on_deliver` hook for mqtt v5 compatibility

### ISSUE THREAD

**Issue by manifest** [vernemq/vernemq#1098]
When MQTT v5 client publish a message and MQTT v3 client receives it, there is no way to process MQTT Properties of the message.

### Environment

- VerneMQ Version: 1.7.1
- OS: macOS, Linux

### Actual behaviour

```erlang
%% Publishing the message using MQTT v5 client
{ok, C} = emqx_client:start_link([{proto_ver, v5}, {host, {192,168,99,100}}, {port, 1883}, {client_id, <<"test-1">>}]),
emqx_client:subscribe(C, <<"foo">>, qos1),
emqx_client:publish(C, <<"foo">>, #{'User-Property' => [{<<"key">>, <<"val">>}]}, <<"{\"payload\":\"bar\"}">>, []).
```

```erlang
%% Processing the message in a delivery hook
on_deliver(_Username, _SubscriberId, _Topic, Payload) ->
    error_logger:info_report([{payload, Payload}]).
```
```
2019-03-04 03:30:26.622 [info] <0.444.0> payload: <<"{\"payload\":\"bar\"}">>
```

### Expected behavior

Having an additional argument `Properties` to the `on_deliver` hook that contains empty map for messages sent using MQTT v3 protocol or map with MQTT Properties if messages sent using MQTT v5.

**Comment by dergraf** [comment]
@manifest thanks for opening. If your subscriber is an MQTTv5 client it should actually call the `on_deliver_v5` hook, which has the properties as an argument. See https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_mqtt5_fsm.erl#L1407
I wonder why it is calling `on_deliver` instead of `on_deliver_v5`. @larshesel any clues?

**Comment by larshesel** [comment]
I don't think @manifest has the problem that he has an MQTT v5 subscriber and the `on_deliver` hook is called in that case - IIUIC it's the question if it would be possible to also support the properties in the MQTT v3/4 context (in the `vmq_mqtt_fsm.erl` state machine). The reason why we so far haven't added properties to the `on_deliver` hook in MQTT v3/4 state machine is simply because we must be backwards compatible. We could of course add a new hook ( `on_deliver2`)  - but on the other hand this adds more complexity both in the finite state machine, documentation etc as well as for the plugin developer.

MQTT v3/4 and v5 already works together, but if one wants the full power of MQTTv5 then all clients need to be using MQTT v5 - at least for the time being.

**Comment by manifest** [comment]
Lars Hesen is right, for the case described above, subscriber is MQTT v3 client, that is why `on_deliver` is called. The problem is to deliver MQTT Properties of a message from MQTT v5 client to MQTT v3 client. Currently it's only possible encoding properties into payload. If we were an additional argument for `on_deliver` hook, we would be able to deliver MQTT Properties without modifying the payload of the message, without any overhead.

**Comment by manifest** [comment]
> all clients need to be using MQTT v5
That is impossible for our case unfortunately, because of the current status of the MQTT 5 support in client libraries.

**Comment by larshesel** [comment]
ok. I don't see how to solve this without being backwards incompatible or introducing a new hook in the mqtt v3/v4 fsm, neither of which I think are acceptable options. I'll tag this for 2.0 so we can consider this then.

**Comment by larshesel** [comment]
I'll close this for now as we've tagged it with the vernemq 2.0 tag so we can find it later.
