### ISSUE TITLE
Add 'correlation_data' and 'response_topic' modifiers

### ISSUE THREAD

**Issue by manifest** [vernemq/vernemq#1099]
To allow MQTT v3 and MQTT v5 clients working on the same broker and interchanging messages, we need a way to set MQTT Properties from the `on_delivery_m5` hook.

We already can implement basic publish and use `user_propery` modifier. This proposal is to expand that feature and add support of request-response messaging pattern by allowing to set `corelation_data` and `response_topic` properties.

### Environment

- VerneMQ Version: 1.7.1
- OS: macOS, Linus

### Expected behavior

Ability to set `corelation_data` and `response_topic` modifiers from `on_delivery_m5` hook.

**Comment by larshesel** [comment]
Thanks for opening this issue. I think being able to modify the properties on the `on_delivery_m5` hook makes sense as this is in the context of the recipient. Is the idea that a plugin would be responsible for adding the request/response information instead of having the clients handle that? What would such a flow look like?

**Comment by manifest** [comment]
In our case we have MQTT v3 clients that send payload and properties folded into an JSON envelope `{"payload": _, "properties"}`. To deliver such a message to MQTT v5 client we may unfold the envelope and send payload and properties separately. That could be done only within VerneMQ plugin (not a client) and for that we need an ability to set `user_property`, `correlation_data` and `response_topic` properties at the moment.

**Comment by larshesel** [comment]
Fixed in #1104
