### ISSUE TITLE
auth_on_publish webhook seems to have a slow request buffer

### ISSUE THREAD

**Issue by ermalguni** [vernemq/vernemq#1109]
Hello,

we are experimenting with Vernemq and the webhooks. Currently we have setup auth_on_{register,publish,subscribe}. All is fine from the configuration perspective, i.e. the webhooks are being called and the cache seems to be working. The only strange thing is that we wrote a script to load test the Vernemq and the webhooks integration. It seems that even after stopping the load tester the publish webhook is still being called for a few more seconds(~9-10 seconds). The webhooks seems to barely have any load. Is there any way to make the webhook calling even faster?

**Comment by larshesel** [comment]
Hi, it's hard to say anything without first understanding the problem in more detail. What scale are we talking here? Could you put some numbers on it? How many sessions how many connects/subscribes/publishes?

So you see your webhook endpoint being called after the test has finished, this usually happens because either 1) the endpoint cannot process the requests fast enough or 2) the connection pool is too small (combined with the processing time at the endpoint). For each hook <-> endpoint there is a default connection pool of size 100 - you could try to increase this size by setting `vmq_webhooks.pool_max_connections=SomeLargerValue` in the `vernemq.conf` file. But without understanding the problem more in detail I don't know if it'll mean anything.

**Comment by ermalguni** [comment]
Hi @larshesel thanks for your answer. The `pool_max_connections` did it. Closing this issue now.

**Comment by larshesel** [comment]
ok - awesome to hear!
