### ISSUE TITLE
[Question] Removing checks for the fixed header

### ISSUE THREAD

**Issue by ermalguni** [vernemq/vernemq#1131]
We have a client that is sending the wrong connect fixed header and vernemq is correctly not allowing that connection. Unfortunately we cannot change that client. I wanted to know where in the code can I disable that check and then recompile and install vernemq.

**Comment by ioolkos** [comment]
Hi @ermalguni hm... that's quite a challenge.
I think it's not just a matter of disabling a check. Parser side, the functions are here: https://github.com/vernemq/vernemq/blob/master/apps/vmq_commons/src/vmq_parser.erl#L54
But honestly, I'm not even sure about any downstream issues that could arise after one starts to change the parser at byte level.

Anyone, feel free to chime in with ideas on that.

**Comment by larshesel** [comment]
@ioolkos is right - you'd have to modify the parser code - which may or may not be trivial. If this is a single client it might be easier to write a very simply proxy which rewrites the header to something correct and that client the connects to the proxy.

**Comment by loguntsov** [comment]
@ioolkos @larshesel 
i was hired by @ermalguni to fix problem and modify VerneMQ.

So i found there is type mistake for resulted parameters which caused crash.

Function parse from any parser (depends from version of protocol) can return this result:

```{{ error, Reason }, Rest} when is_binary(Rest)```

so it cause problem in case clause.
I made fix of this. Just 2 lines since this code:
https://github.com/loguntsov/vernemq/blob/291019c1e6ab63d34fa70b3a817a7a73219e9518/apps/vmq_server/src/vmq_mqtt_pre_init.erl#L56

Pls pull it into upstream. Thank you.

**Comment by larshesel** [comment]
Hi

Could you please create a PR and also provide a test case or test data (the connect packet which causes the problem) so we can understand this better?

**Comment by larshesel** [comment]
If I understand your change correctly, then this handles an error case so it doesn't crash, right? Does this also handle the original problem?

**Comment by loguntsov** [comment]
Crash was fixed, but problem was fixed by another code. These 2 lines what i mentioned above fixes crash when it can't recognize variable.
Just see this line: https://github.com/vernemq/vernemq/blob/5d5a16737e39b321180c4361c8510e291d99565f/apps/vmq_commons/src/vmq_parser.erl#L69
parse function creates tuple with result and rest of binary.
The result can be mqtt_frame or some error. This result returned by variable function. So the full result will be like this:
{{ error, Reason}, Rest }, but there was no case clause for this result there: https://github.com/loguntsov/vernemq/blob/291019c1e6ab63d34fa70b3a817a7a73219e9518/apps/vmq_server/src/vmq_mqtt_pre_init.erl#L48
so i just added this.
Other things are not related to bug for VerneMQ, but related of bad connection packet from device.

**Comment by larshesel** [comment]
Make sense - please create a PR with the change. Thanks!
