### ISSUE TITLE
max_inflight_messages = 1, shared subscriptions and message ordering

### ISSUE THREAD

**Issue by davideicardi** [vernemq/vernemq#1219]
### Environment

- VerneMQ Version: 1.4.1 (but I can upgrade if necessary)
- VerneMQ configuration:
  - `max_inflight_messages = 1` to ensure order as per documentation
  - `max_online_messages = 99999`
  - `max_offline_messages = 99999`
- Cluster size/standalone: 3

Let's say that 100 devices will publish messages to my VerneMQ cluster using a topic like: `{device-client-id}/XYZ` with **QoS 1**.
Then I have a Java application installed on 3 VMs that subscribe to MQTT with QoS 1 using a shared subscription `$share/MYAPP/+/XYZ`.

### Expected behavior

I expect that given the fact that messages are sent to 100 different topics and `max_inflight_messages = 1` I will get one message from each topic, so potentially each subscriber will get 100 messages concurrently.

### Actual behaviour

From my experiment my app receive a single message at the time on each subscriber, no matter how many devices/topics are used.
The effect is that the throughput is very low, because the only way to scale is to add more subscribers.

Some related questions:
1. `max_inflight_messages=1` is applied for subscriber, for topic or for subscription?
2. Is message order guaranteed using shared subscriptions?
3. If instead of subscribing to `$share/MYAPP/+/XYZ` I will subscribe to `$share/MYAPP/DEVICE_1/XYZ`, `$share/MYAPP/DEVICE_2/XYZ`, `$share/MYAPP/DEVICE_3/XYZ`, etc... can I achieve a better throughput?

thanks!

**Comment by larshesel** [comment]
Hi, 

This sounds strange. Can you please try to reproduce on the latest version (1.8.0)? AFAIUI the `max_inflight_messages` also applies to the inflight messages on the subscriber side, perhaps the documentation is a bit misleading - I'll have to check - but that would mean only one message arrives at a subscriber at a time. 

Regarding message order then the same guarantees as always hold for the shared subscriber group. Within each member of the group we of course can't guarantee the ordering as the subscribers are concurrent units - one may be slower than others or be offline a while etc etc.

**Comment by davideicardi** [comment]
Thanks @larshesel! I will try with the new version. I will write back to you next days on this.

Regarding shared subscriptions and message order: do you mean that it can happen that if a single device sends messages A, B, C on the same topic I can potentially read message A from node 1, message B from node 2 and message C from node 3? And potentially process messages out of order?
In this case I think that probably I cannot use shared subscriptions ...
I have configured `shared_subscription_policy = prefer_local`, don't know if this is important for ordering ...

**Comment by davideicardi** [comment]
To better explain, my expectation is that I will receive a message on any subscriber within the shared subscription group, but only if the previous message is acknowledge. It is correct?

**Comment by larshesel** [comment]
> Regarding shared subscriptions and message order: do you mean that it can happen that if a single device sends messages A, B, C on the same topic I can potentially read message A from node 1, message B from node 2 and message C from node 3?

Absolutely. The distribution is random within the group. So two messages published by a single publisher may end up with two different shared subscribers in the group.



>  my expectation is that I will receive a message on any subscriber within the shared subscription group, but only if the previous message on the same topic is acknowledge. It is correct?

That is incorrect. This would imply that there is coordination between two clients subscribed to the same shared subscription which is not the case.

I hope this helps. Perhaps it would help to go through our documentation on shared subscriptions here: https://docs.vernemq.com/configuration/shared_subscriptions and perhaps have a look at the details in the MQTT spec as well: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901250

**Comment by davideicardi** [comment]
But if VerneMQ doesn't wait until the previous message is acknowledge the effect is that the message order is no more guaranteed, also with `max_inflight_messages = 1`.
So basically if message order is important then we cannot use shared subscription. Correct?

According to MQTT spec ordering is guaranteed when `max_inflight_messages = 1`, but it doesn't specify it in the shared subscription section:
> If both Client and Server set Receive Maximum to 1, they make sure that no more than one message is “in-flight” at any one time. In this case no QoS 1 message will be received after any later one even on re-connection. For example a subscriber might receive them in the order 1,2,3,3,4 but not 1,2,3,2,3,4. Refer to section 4.9 Flow Control for details of how the Receive Maximum is used.

**Comment by larshesel** [comment]
> But if VerneMQ doesn't wait until the previous message is acknowledge the effect is that the message order is no more guaranteed, also with `max_inflight_messages = 1`.
> So basically if message order is important then we cannot use shared subscription. Correct?

This is essentially correct. The thing to understand is that shared subscriptions are for distributing messages between a set of clients, and the distribution decision (which client shall handle the message) is done as part of the routing and the message is afterwards handled by the client session on the broker. It is between the client session on the broker and the client the `max_inflight_messages` takes effect.

If the entire shared subscriber group were only able to handle a single message at a time and had to wait for the ack for the client to send the next one, then that would go against the entire idea of shared subscriptions which is to be horizontally scalable.

In the case of shared subscribers the `max_inflight_messages` works as intended. If messages 1,2,3 are published (in that order) to the shared subscription and one client handles messages 1,3 and another client message 2, then the one handling 1,3 will get them in that order, one after the other, due to the `max_inflight_messages` setting. But it is entirely possible that the client handling message 2 will get that temporally later than when the first client received message 3. This is due to physics: who knows how long time it took to route message 2 over the network compared to the other messages?

**Comment by davideicardi** [comment]
Thanks @larshesel !

**Comment by chrihartl** [comment]
@larshesel
I found this thread very helpful. I understood that `max_inflight_messages=1` will ensure time ordering on the side of each subscriber/client (but of course not across all subscribers involved in a shared subscription - that would totally go against horizontal scaling as you explained).

But I am still unsure about this:

Does the above setting guarantee time ordering
(a) only per client, across all subscribed topics
(b) or even per client AND per subscribed topic individually?

**Comment by ioolkos** [comment]
@chrihartl 

For every incoming message the shared subscriber policy will make an individual decision and put the message into the queue of 1 chosen shared subscriber client.
That queue is exclusive to 1 consumer and its FIFO.

With `max_inflight_messages = 1` you ensure that only the first message at the head of the queue "jumps" to the consumer and then waits for an ACK for that, before it allows the next message in the queue to jump. There are messages from multiple publishers and resulting from multiple topic matchings in that queue.

So, I guess the ordering is as per your item `(b)`.
I would not call this "time ordering". Especially running in cluster formation, there is not much of a concept of wallclock time.

As a side note, I've always found the concept of Ordered Topic somewhat misleading in the MQTT spec:
https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718105
A Topic is not a queue.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by chrihartl** [comment]
@ioolkos 
I think I understood most of what you explained and you made a very good point about the term "time ordering" in a cluster context (with multiple publishers and subscribers).

However, in a special context with a single publishing client (P), a single subscribing client (S), and a handful of topics (A, B, C), the question of how `max_inflight_messages = 1` influences the temporal order of messages sent by P and received by S still exists.

In my particular case, P uses QoS=2 to publish messages to the VerneMQ broker, for instance, in this order:
A1, A2, C1, B1, A3, B2, C2, B3, C3 (where "A1" means "message 1 sent to topic A", and so on) and S subscribes to topics A, B, C (not using a shared subscription).

My remaining questions concerning this scenario in combination with `max_inflight_messages = 1` are:

Question 1: Does VerneMQ guarantee that these messages arrive at S in the exact order as given above, or only, that the A's are ordered and the B's are ordered and the C's are ordered?

Question 2: It might happen that messages are published in very quick succesion, and sometimes, due to network problems between the subscriber and the broker, a QoS=2 message does not reach its destination (S) on the first attempt. In this case, VerneMQ will try to resend the message after a certain (configurable) waiting time, e.g. 20 seconds. For example, if delivery of C1 fails at first - will all the other messages in the S-queue have to wait until resending C1 succeeds? Or will only the other messages of topic C (C2, and C3) have to wait (but not the messages of topics B and C)? Or will, in this particular case, C1 be put at the end of the queue and C2 and C3 will be sent before C1 ("because an error happened")?

**Comment by ioolkos** [comment]
Note that the inflight window is something that the publisher decides. The `max_inflight_message` config is applied at the outgoing side of the broker.

What Verne does is it processes the messages from a publisher in the order it gets them. So that's an exact order which encompasses a per topic order. 
The result of that processing is a consumer queue, where messages are ordered FIFO. The order of that queue will never be changed, it has no priority queue features. Even QoS 0 messages will stay stuck in the queue, in case you are blocked at the head due to `inflight` 1, and a non-completed QoS handshake.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
