### ISSUE TITLE
VerneMQ 1.8.0 can't be installed on Ubuntu running in WSL

### ISSUE THREAD

**Issue by Blindpupil** [vernemq/vernemq#1235]
Error:

`$ sudo dpkg -i vernemq-1.8.0.bionic.x86_64.deb`
Selecting previously unselected package vernemq.
(Reading database ... 28645 files and directories currently installed.)
Preparing to unpack vernemq-1.8.0.bionic.x86_64.deb ...
Unpacking vernemq (1557911354:1.8.0) ...
Setting up vernemq (1557911354:1.8.0) ...
Adding group `vernemq' (GID 115) ...
Done.
Adding system user `vernemq' (UID 111) ...
Adding new user `vernemq' (UID 111) with group `vernemq' ...
Not creating home directory `/var/lib/vernemq'.
System has not been booted with systemd as init system (PID 1). Can't operate.
Created symlink /etc/systemd/system/multi-user.target.wants/vernemq.service → /lib/systemd/system/vernemq.service.
System has not been booted with systemd as init system (PID 1). Can't operate.

### Environment

- VerneMQ Version: 1.8.0
- OS: Windows 10 - 1903

### Expected behavior

- Install finishes successfully. 

### Actual behaviour

- Install doesn't finish because of error. 

**This error doesn't happen when installing VerneMQ Version: 1.7.1**

**Comment by ioolkos** [comment]
@Blindpupil thanks for opening the issue. So it must be related to the new setup using systemd. 
Do you see this error when upgrading from 1.7.1 to 1.8.0, or also when installing 1.8.0 on a new system?

**Comment by Blindpupil** [comment]
I saw the error only when installing 1.8.0 on a new WSL (Ubuntu 18.04). 
This was my first time trying to install VerneMQ

**Comment by dergraf** [comment]
@Blindpupil Since 1.8.0 the VerneMQ packages fully integrate with Systemd instead of using the old init files. Therefore Systemd is required to run the official VerneMQ packages. I am not sure about the status of SystemD on WSL, but https://github.com/systemd/systemd/issues/8036 indicates that is it a pending feature request.

Alternatively you can build a custom release using `make rel` on WSL (I guess that should work) and use such a release to run VerneMQ.

Sorry that I don't have a better answer for you right now.
