### ISSUE TITLE
vmq_diversity: JSON decode/encode roundtrip changes null to "null"

### ISSUE THREAD

**Issue by okofish** [vernemq/vernemq#1286]
### Environment

- VerneMQ Version: 1.6.2
- OS: Docker (erlio/docker-vernemq:1.6.2)

### Expected behavior

The following Lua code should log `{"abc":null}`:
```
log.info(json.encode(json.decode("{\"abc\": null}")))
```

### Actual behaviour

The code logs `{"abc":"null"}` instead.

It's possible that #1082 fixed this; I can't test on 1.8.0 right now.

**Comment by larshesel** [comment]
This hasn't been fixed. 

This is due to the fact that `null` doesn't have a representation in LUA. `nil` doesn't work as in LUA this is equivalent to a missing key. Different LUA json libraries handle this differently. Ours converts `null` into `"null"`. The same problem exists with converting an empty LUA table which in JSON can be either a JSon object or an array. Either way the libraries have to make some kind of decision. This means json encode/decode operations are not inverses in LUA and can in general not be. 

If you have a good idea how to handle it we'd love to consider it.

**Comment by okofish** [comment]
OK, I thought it might be something like that. I understand the difficulty.

Perhaps json.encode could convert `"null"` back into `null` then? Maybe there could be a second argument for both functions to change the token string `null` gets converted to/from, as some users might theoretically have actual string `"null"`s in the data they're de/encoding.
