### ISSUE TITLE
TLS certificate data from webhooks

### ISSUE THREAD

**Issue by muhamedcpqd** [vernemq/vernemq#1300]
Hello!

These days i'm trying to develop some webhooks over the 'auth_on_register' hook using  nodejs endpoints. From the payload delivered of this webhook, i  gotten some informations like password from the body payload, however, because i'm using TLS for authentication what i really need is to access information like the peer certificate. Its there some way to get those TLS data from verne? if there is a way, can we get using some webhook or user custom plugin?

**Comment by larshesel** [comment]
Hi, TLS information is not available in the plugin system. You can configure the common name from the cert to be used instead of the MQTT username. See https://docs.vernemq.com/configuration/listeners#sample-ssl-config.

You can also give a hint to the plugin implementations what listener it was by giving it a special mountpoint like for instance `tls`.

Hope this helps.
