### ISSUE TITLE
prometheus connected clients

### ISSUE THREAD

**Issue by caevv** [vernemq/vernemq#1303]
Is it possible to get `vmq-admin session show` from prometheus?
I'd like to have the client ids and the statuses of the clients on a Grafana board.

**Comment by ioolkos** [comment]
@caevv thanks for your question. 
The thing here is that ClientIDs and their status is not a gauge or counter style metric, so they can't be aggregated.

What you're looking for is basically some sort of presence service/device management backend/SCADA host. This can be fairly easily done with MQTT but Prometheus is probably not the optimal approach her.
Also, thinking about scale... how would you actually plot status of thousands or even millions of devices.

@ all: open for ideas here. let me know if you have better ideas @caevv or more details

**Comment by chrihartl** [comment]
@larshesel 

### Idea

In order to make individual VerneMQ clients (client ids) monitorable through Prometheus but still avoid the problem of monitoring the status of an unbound number of clients, provide the following feature:

- By default, monitor each client individually (see below)
- Optionally allow configuring a list of "monitoring client id patterns" (a list of regex expressions against which client ids are matched), such that client IDs are grouped instead of considered individually for the purpose of monitoring.

For each monitored individual client - or, if configured, class of clients - you would get various metrics, for example
CLIENT_STATUS{client_id_pattern='a', status='connected'}  (counter)
CLIENT_CONNECTION_TIME{client_id_pattern='a'} (histogram)

### Rationale

If there is just a handful (bounded number) of clients, the default monitoring behaviour would just work.

On the other hand, for the case of a large-scale system one would configure something like:
```
monitoring_client_id_patterns:
  - 'africa-*'
  - 'arab-states-*'
  - 'asia-pacific-*'
  - 'europe-*'
  - 'middle-east-*'
  - 'north-america-*'
  - 'south-latin-america-*'
```

and get the above Prometheus metrics (in the form of labelled counter metrics or histograms) for client classes that potentially contain large numbers of clients.

This would be a pretty useful extension of the already awesome set of VerneMQ metrics available through Prometheus.

**Comment by chrihartl** [comment]
I redirected my previous comment to a new feature request: https://github.com/vernemq/vernemq/issues/1859
