### ISSUE TITLE
postgres db for authentication transactions per second.

### ISSUE THREAD

**Issue by brolly759** [vernemq/vernemq#1329]
I setup everything successfully and everything is working. I am looking at the current implementation of postgres db usage. I have a separate server hosting postgres and noticed the transactions per second increase when you have auto connect  on failure. So theoretically a user can spam connections to the server and eventually crash the database flooding the transactions per second. It seems that Vernemq queries the db for every connection coming in. Is there a way to create some type of buffer locally within VerneMQ that copies the database every x seconds so no matter what the transaction count, the database hit is minimal? 

Is there some type of DDOS prevention for VerneMQ?

Thanks!

**Comment by larshesel** [comment]
>  I have a separate server hosting postgres and noticed the transactions per second increase when you have auto connect on failure.

Not sure I understand this part?

> So theoretically a user can spam connections to the server and eventually crash the database flooding the transactions per second.

Yes, this is correct. If it's not the database it would be another component down the chain - i.e., the slowest part where things start to accumulate. 
> Is there some type of DDOS prevention for VerneMQ?

Not out of the box. You can combine the output of the logs with fail2ban or similar as well as using a loadbalancer which throttles new connections etc. It is also important that even without an intentional DDOS you have to be able to handle all clients reconnecting at the same time in case of a network failure etc, so even for that one should measure what max capacity of the system is and design protection mechanisms for that.

Hope this helps.

Closing this as this is more a question rather than a bug report or feature proposal.
