### ISSUE TITLE
Cant set retain: true while publishing from a plugin 

### ISSUE THREAD

**Issue by damouse** [vernemq/vernemq#1444]
I am publishing from an elixir plugin as so:

```
        reply = publish_fun.(["some", "topic"], "somemessage", %{retain: true, qos: 1})
```

Where publish_fun comes from:

```
        {module, fun, args} = registry_mfa
        {register_fun, publish_fun, _sub_and_unsub_fun} = apply(module, fun, args)
        true = is_function(register_fun, 0)
        true = is_function(publish_fun, 3)
        :ok = register_fun.()
        {:ok, %{publish_fun: publish_fun}}
```

Some code changed for the purpose of the demo. The publish works, but is not retained-- a client connected and subscribed at the time of the publish will receive the publish, but one that connects after the publish will not. I've been looking through the bridge source, and it all seems to be working. Is there some trick to setting these options?

**Comment by ioolkos** [comment]
@damouse the 3rd argument has to be a Map. You should be able to override the retain flag using that. `#{retain => Retain}`
Retain has to be a flag (`true` or `false`)

**Comment by damouse** [comment]
My plugin is written in Elixir, and I am told the syntax you pasted is for Erlang Maps-- is that incorrect?

**Comment by ioolkos** [comment]
Yeah, sorry, that was Erlang syntax. 
Wonder if this is related to https://github.com/vernemq/vernemq/issues/1420

**Comment by tsturzl** [comment]
We're not currently using a bridge, unless clustering relies on some bridge routines, but I believe this is happening on a standalone broker also.

**Comment by ioolkos** [comment]
@tsturzl clustering is not related to bridge routines.

But currently the bridge has the following issue: normally, when a message is published (over the vmq_reg module), Verne ensures that the outgoing retain bit is set to false, even if it's set to true on the incoming side.
This is the right thing to do (according to MQTT spec) for normal clients. It's wrong for an outgoing publish over a bridge which needs the retain flag to be set, so that the message can also be retained on that target broker.

It seems that you want to achieve something similar with your plugin, and might be affected by the same issue: the publish gets through but without the retain flag set.

**Comment by ioolkos** [comment]
To add to this: the `vmq_reg` module has no access to the MQTT protocol version. The MQTT state machines obviously know the protocol version and they connect over `vmq_reg:publish/4` to vmq_reg. We could add the protocol version to the publish function, handing it over to vmq_reg where the retain flag could be handled depending on the protocol version. 

I'm not entirely clear what your plugin is about. Can you add a little more context?
