### ISSUE TITLE
Vernemq Message queue increasing without any limit

### ISSUE THREAD

**Issue by natrajT** [vernemq/vernemq#1449]
### Environment

- VerneMQ Version:1.10.0
- OS:ubuntu 18.04
- Erlang/OTP version (if building from source): Erlang/OTP 22
- VerneMQ configuration (vernemq.conf) or the changes from the default
max_online_messages = 50000
- Cluster size/standalone: 2
### Actual behaviour
![image](https://user-images.githubusercontent.com/11175886/76289554-688c5100-62cf-11ea-94d6-fa445b15c4f8.png)

Message queue size is increasig witthout any upper limit. 

Need help in understanding the below queries:
1) Why the message queue is increasing?
2) How to make the vernemq process the messages faster?
3) Is there any way to identify which topic has highest messages? 
4) Any way to purge the message queue before server running out of memory?

**Comment by ioolkos** [comment]
1. Why the message queue is increasing?
Because you fill it up. This means your consumers or Verne are too slow. Or your publisher too fast.
   2. How to make the vernemq process the messages faster?
Give it more CPU. Side note: why do you think your issue is making VerneMQ faster?
   3. Is there any way to identify which topic has highest messages?
Topics don't have messages. Look at `sudo vmq-admin session show --help` if you want information on number of online messages for sessions/queues. 
   4. Any way to purge the message queue before server running out of memory?
If you allow 50k online messages (per session) then you probably want to have the RAM for that. (also look at your payload size). Side note: can you imagine what 'purging' would mean on a running session? it would break MQTT spec. (Yes, so does load-shedding of messages in case you configure max_online_messages which should be your instrument for this)
