### ISSUE TITLE
Confusion over license

### ISSUE THREAD

**Issue by robputt** [vernemq/vernemq#1487]
Hello,

I am confused about the license for VerneMQ...

The EULA says 

"You must not, directly or indirectly: (a) modify, translate, adapt, or otherwise create derivative works or improvements, whether or not patentable, of the Software or any part thereof; (b) reverse engineer, disassemble, decompile, decode, or otherwise attempt to derive or gain access to the source code of the Software or any part thereof; (c) remove, delete, alter, or obscure any trademarks or any copyright, trademark, patent, or other intellectual property or proprietary rights notices provided on or with the Software, including any copy thereof; (d) rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer, or otherwise make available the Software, or any features or functionality of the Software, to any Third Party for any reason; (e) use the Software in violation of any law, regulation, or rule; or (f) use the Software for purposes of competitive analysis of the Software, the development of a competing software product or service, or any other purpose that is to the Octavo Labs’s commercial disadvantage."

However, the source code is open source and published to Github and the EULA directly contradicts the Apache 2 License in the Github repository that states that...

"Redistribution. You may reproduce and distribute copies of the
   Work or Derivative Works thereof in any medium, with or without
   modifications, and in Source or Object form, provided that You
   meet the following conditions:

   (a) You must give any other recipients of the Work or
       Derivative Works a copy of this License; and

   (b) You must cause any modified files to carry prominent notices
       stating that You changed the files; and

   (c) You must retain, in the Source form of any Derivative Works
       that You distribute, all copyright, patent, trademark, and
       attribution notices from the Source form of the Work,
       excluding those notices that do not pertain to any part of
       the Derivative Works; and

   (d) If the Work includes a "NOTICE" text file as part of its
       distribution, then any Derivative Works that You distribute must
       include a readable copy of the attribution notices contained
       within such NOTICE file, excluding those notices that do not
       pertain to any part of the Derivative Works, in at least one
       of the following places: within a NOTICE text file distributed
       as part of the Derivative Works; within the Source form or
       documentation, if provided along with the Derivative Works; or,
       within a display generated by the Derivative Works, if and
       wherever such third-party notices normally appear. The contents
       of the NOTICE file are for informational purposes only and
       do not modify the License. You may add Your own attribution
       notices within Derivative Works that You distribute, alongside
       or as an addendum to the NOTICE text from the Work, provided
       that such additional attribution notices cannot be construed
       as modifying the License.

   You may add Your own copyright statement to Your modifications and
   may provide additional or different license terms and conditions
   for use, reproduction, or distribution of Your modifications, or
   for any such Derivative Works as a whole, provided Your use,
   reproduction, and distribution of the Work otherwise complies with
   the conditions stated in this License."

I am massively confused here if I build a SaaS product using VerneMQ the EULA pretty much says I am not allowed to sell it or market it as it, in which case I need to ditch VerneMQ and use a properly open-sourced solution, but the Apache license for VerneMQ suggests I am free to modify it and make it available to others in whichever way as long as I retain the original attribution and document changes as per the above. Please can somebody clarify how this works and which license takes precedent?

Best Regards,

Rob

**Comment by ioolkos** [comment]
The EULA is for the compiled Linux packages and our Docker images, starting from Release 1.10.0.
(we don't build those packages 'for free' any more).

If you don't want to use those, you can compile/build everything yourself. Source code is open source, Apache2, don't worry.

**Comment by robputt796** [comment]
Ok, so providing I compile from the source I am all good to assume the EULA doesn't apply to me only the terms of the Apache 2.0 license?

In this case, does anyone in the community want to start packaging a community release of this from the Apache 2.0 licensed source code with me?

**Comment by ioolkos** [comment]
Yes, to your first question. Note that you absolutely can build commercial solutions with our compiled packages.
This is a somewhat similar approach to what Chef.io does (obviously in a much bigger context): https://blog.chef.io/chef-software-announces-the-enterprise-automation-stack/

**Comment by ahmedwahdan** [comment]
> Yes, to your first question. Note that you absolutely can build commercial solutions with our compiled packages.
> This is a somewhat similar approach to what Chef.io does (obviously in a much bigger context): https://blog.chef.io/chef-software-announces-the-enterprise-automation-stack/

Could I use the build image from source code in commercial product?
What is the difference between using pre-build image and build it myself? any different features?

**Comment by ioolkos** [comment]
You can use everything that is open sourced here, build it and use it commercially.
You can also download & use our pre-compiled packages (with the EULA addition), and use them commercially for a usage fee.

**Comment by ahmedwahdan** [comment]
This what I understand so far, but my question again is there any difference that requires a usage fee?

**Comment by ioolkos** [comment]
Functionally (MQTT spec etc), no difference currently. The work & optimization we put in. It allows up to keep VerneMQ open source as is. The alternative is offering essential features as closed source only (clustering, persistence), like others do.

**Comment by robputt796** [comment]
@ahmedwahdan to my understanding there is no difference in the functionality I think what is happening here is...

- Octavo Labs created VerneMQ and wanted to offer an opensource product OR are obliged to release their code under some opensource license.
- Octavo Labs take the opensource project at some point in time and create a package, perform some bug fix maybe optimisation/validation and release the packages.
- Octavo Labs require in the EULA if you use said packages for commercial reasons you pay them some fee.

The problem is there are no community packages so you either must:
- Pay Octavo Labs if you wish to use their packages for a commercial project.
- Build the project from source and validate it works/test it yourself and then Apache 2 license applies and you do not need to pay Octavo anything even for commercial use.

To make it easier for people using the Opensource Apache 2 licensed option what we could do with is:
- Creating CI mechanism to package for .deb and .rpm automatically from the repository.
- Create CI to deploy it to some gate and test the packages against common LTS operating systems.
- Publish the community packages somewhere which have passed the validation.

This way people can then choose either:
- Octavo Labs packages which are paid for commercial use.
- The community packages which are free and means the user doesn't need to compile from scratch / configure SystemD etc...
- Compile from scratch and configure how they wish.

If there are any keen people out there who'd like to help do some community packaging for this it would be great.

I don't mind companies charging for support and consultancy for users of opensource projects but I have to admit I am not keen on companies making the opensource / community release of their product harder to use than the commercial release just for the sake of converting sales. It doesn't really seem in the spirit of the open-source movement.

**Comment by ahmedwahdan** [comment]
@robputt796 
I got it, and agree with you regarding the point of restricting the packages for sales.
I don't have much experience but I for sure will help in case there is an initiative to create community packages.

**Comment by robputt796** [comment]
@ahmedwahdan which OS do you target? I am currently targeting Ubuntu 20.04 for my project so I'll probably make some deb packages for myself and upload them somewhere if others want to use them, I am hoping you are using some RedHat variant and are thinking of making RPM packages... 📦

**Comment by ahmedwahdan** [comment]
l believe my colleague will build a docker image. 
Please share with me the details of the package you will build.

**Comment by GTP95** [comment]
> l believe my colleague will build a docker image.
> Please share with me the details of the package you will build.

Did you build it? Is it published somewhere? I'm asking because I'm about to create one myself, but I don't want to create an unnecessary duplicate.
