### ISSUE TITLE
Syslog dependency fails to build on OTP 23.0

### ISSUE THREAD

**Issue by ioolkos** [vernemq/vernemq#1506]
Just checked whether Verne builds on Erlang 23.0 released today.
But it fails with
`/usr/bin/ld: cannot find -lerl_interface`
while compiling and linking syslog.

**Comment by codeadict** [comment]
Yep, had the same issue, it is also kinda problematic on OSX Catalina

**Comment by codeadict** [comment]
Alternatively, the https://github.com/Vagabond/erlang-syslog package is more recently updated but basho's lager_syslog is not anymore so forking it and updating it to the latest erlang-syslog may be a good idea. There is also https://github.com/schlagert/syslog which RabbitMQ uses and it provides integration for lager and OTP 21,s new logger and as a plus, it is written in pure Erlang instead of a C port.

**Comment by codeadict** [comment]
This could be closed now
