### ISSUE TITLE
Cluster-Wide Session Re-Authorization

### ISSUE THREAD

**Issue by ssmiller25** [vernemq/vernemq#1541]
### Environment

- VerneMQ Version:  1.10.2
- OS:  Linux (Kubernetes)
- Erlang/OTP version (if building from source): N/A
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 3 node

### Expected behavior

`vmq-admin session reauthorize` works for a client from any cluster node.

### Actual behaviour

Periodically we issue vmq-admin command to re-authorize subscriptions for a client in each node and it ends up killing the subscription.

Might be related to [#1124](https://github.com/vernemq/vernemq/issues/1124)

**Comment by ioolkos** [comment]
@ssmiller25 Thanks. I don't understand from your description what you do. 

`vmq-admin session reauthorize` sometimes works, sometimes not, killing a subscription? 

What does killing the subscription mean? what do you see logged? What auth plugins do you use?

**Comment by gsingh395** [comment]
@ioolkos adding to what @ssmiller25 said, we have a 3 node cluster setup and there's a shell script that runs on each node which periodically gets the list of connected clients using "vmq-admin session" and issue "vmq-admin session reauthorize" for each client. Since in cluster setup, the list contains the clients that are connected to other nodes as well, script ends up calling reauthorize command for those clients as well which ends up killing the subscription and the client stops getting messages. We have written a lua plugin with auth_on_subscribe hook which does gets called when "vmq-admin session reauthorize" is issued. In non-cluster setup everything works as expected.

**Comment by ioolkos** [comment]
@gsingh395 @ssmiller25
Okay, thanks for the additional information. Will have to check this.
In the mean time, couldn't you add `--node` to your `vmq-admin session` command, and then do some filtering or sorting in the script (so that you only call reauthorization for local sessions)?

**Comment by gsingh395** [comment]
Thanks @ioolkos  I wasn't aware you can query node column with `vmq-admin session` command. @ssmiller25 this might work for us.

**Comment by ioolkos** [comment]
`vmq-admin session show --help` shows you all the options.

**Comment by ssmiller25** [comment]
Thanks @ioolkos.  That solution will work for us!
