### ISSUE TITLE
Viewing Unauthorized clients using vmq-admin command

### ISSUE THREAD

**Issue by achandana** [vernemq/vernemq#1662]
### Environment

- VerneMQ Version:1.10.3
- OS:EC2 instance
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

Need help on how can we find the unauthorized clients try to connect Vernemq using vmq-admin

**Comment by ioolkos** [comment]
@achandana You can't find unauthorized clients using `vmq-admin`. (VerneMQ would need to store unauthorized ClientIDs for that, which it does not, of course).

You can check the Verne logs for warnings for rejections `due to no_matching_hook_found` or `due to invalid_credentials`. You should see the subscriber ID there.
