### ISSUE TITLE
If max inflight messages set to 1, will the sending of messages slow down?

### ISSUE THREAD

**Issue by FitzLu** [vernemq/vernemq#1677]
### Environment

- VerneMQ Version: 1.10.1
- OS: Amazon Linux 2
- VerneMQ configuration (vernemq.conf) or the changes from the default:
```
modify this:  max_inflight_messages = 1
```

### Expected behaviour

- Publish 1000 messages in 2 seoncds to one topic, subscriber can receive the messages in time

### Actual behaviour

- One minute has passed since the last message was received

**Comment by ioolkos** [comment]
@FitzLu This should not happen, but yes, `max_inflight_messages` affects performance. Broker will send a message and wait for the PUBACK. 
Check on the wire what happens if possible (Wireshark).

Also note that depending on settings as `max_online_messages` the broker might throw away messages to protect slow consumers.
