### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by varnerac** [vernemq/vernemq#1705]
Would you accept a pull request to add an Erlang formatter like [erlfmt](https://github.com/WhatsApp/erlfmt) to the project?

**Comment by ioolkos** [comment]
Tried a while ago, formatter stumbles on certain things (forgot which). There's also the point that it will mess up Git history, or blame, because it'll reformat everything. 
Discussed a little bit here with others: https://github.com/martinsumner/leveled/issues/318
But in principle, I'm open to take the plunge at some point, so why not now.
