### ISSUE TITLE
clean_session always shows true

### ISSUE THREAD

**Issue by onlybytes** [vernemq/vernemq#1708]
Hi

I am connecting to Vernemq from Java. The version is set as 5.0 and i am setting CleanStart to false.
When i run the command, `vmq-admin session show --client_id --offline_messages --topic --qos --statename --clean_session`
the `--clean_session` always shows the value as true.

There is no <sub-command> as --clean_start. Hence, i am assuming that `--clean_session` is used to show the value for MQTT 5.0 as well.

Note: This is working properly when the client version is set as 3.1.1 and CleanSession is set to false.

### Environment

- VerneMQ Version: `1.11.0`
- OS: `CentOS Linux release 7.9.2009`
- Erlang/OTP version (if building from source): `22.3`
- Cluster size/standalone: `Standalone`

### Expected behaviour

- When the **CleanStart** flag is set to false, the `vmq-admin session show --clean_session` should display value as false.

### Actual behaviour

- When the **CleanStart** flag is set to false, the `vmq-admin session show --clean_session` is displaying value as true.

**Comment by ioolkos** [comment]
@onlybytes thanks, that's clearly not intended.
https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_info.erl implements a `vmq_ql_behaviour` and the tables there do not prepare a `--clean_start` flag. 
As you say, we could map this to the `--clean_session` flag, or separate the flags, but then we'd need to set it to `undefind` in case you query it for a v5 session, instead of defaulting to clean_session true.

**Comment by onlybytes** [comment]
@ioolkos thanks for your comment.
For v5 session, defaulting --clean_session to true is confusing. 
A separate flag for `--clean_start` or mapping `--clean_start` to `--clean_session` or setting it to `undefined` will he really helpful.
