### ISSUE TITLE
Is one user/pass capable to connect using multiple client ID based on a pattern?

### ISSUE THREAD

**Issue by nikoladsp** [vernemq/vernemq#1763]
Hi all
I have couple of questions about VerneMQ and this seems to be the right place (Google group seems rather quiet). If I am wrong, please point me in right direction.

Basically, what I am interested in is this: our company has multiple clients (each client is actually also a company) and each client has its own users (company workers). We have Postgres as our back-end DB, and we tried VerneMQ Postgres authentication. 

Now the first question is: can vmq_auth_acl reside in schema other than public? 

Second is: can user/pass combination be used for clients based on some pattern - like user1 with pass1 can connect to MQTT broker using any clientID in form of company1*whatevertextfollows*

If not, is it possible to create our own plugin to do this, since one user can open our web app in many tabs and each tab would need to have separate client id added to table for the same user/pass.

Thank you kindly

**Comment by ioolkos** [comment]
@nikoladsp why does Google group being "silent" makes you not post there ;)
I'd prefer to have non-issue based questions over there. Anyway, don't bother re-posting. It's a lost cause trying to keep user questions off Github... and in the end, fine too :)
I'll answer here when I find time to think about your questions.

**Comment by nikoladsp** [comment]
Thank you. By silent I actually mean dead - just a couple of posts in total. Also I tried on freenode without success, so did not know where else to go - sorry :(

Best regards

**Comment by ioolkos** [comment]
Ok, to issue a couple official judgements:
- Googlegroups: alive
- IRC/freenode: dead (ie not monitored)
- Slack: alive (but invite needed due to no self-invite service currently)

**Comment by nikoladsp** [comment]
Maybe I was looking at wrong group? Is [this](https://groups.google.com/g/vernemq-users) one? There are like 8 posts there

**Comment by ioolkos** [comment]
"like 8 posts". Project must be dead, right.

Yes, it's the official one. I opened Google Group only last year, so that we have an additional, mail-like channel. It's linked on README page.

**Comment by nikoladsp** [comment]
No need for that kind of attitude. 

If you open it, what would you think - honestly? Last post there was 29th October past year so it really does not look like anything is going on in there. On official page there is a link to IRC/freenode also, and yet it is dead as you just told, so not sure why Google group would be different and why are you so offended. And truth to be told, I did not see Google group on [official](https://vernemq.com/community.html) page. 

My company is currently considering using VerneMQ as a broker and all I wanted is to get some info so we can decide shall we use it and if yes-how to utilize it. I am aware that this is not the best place to ask questions, but I did not have any other option - this is why I said at the beginning to point me into the right direction.

I did not accuse you personally for anything or being provocative in any way

**Comment by ioolkos** [comment]
As an open source maintainer you probably get too sensitive to certain things. You also have to suppress that constantly, or you will get attitude-policed and complained about.

"There are like 8 posts there". This triggered that sensitivity, needlessly. (thinking "why not going ahead and make it 9 posts then?")

Well, I apologise for being cynical. And doubly so in view of the fact that there is outdated information (about IRC etc) on the web page, you're totally right about that. Going to fix that, of course.

Let's go back to your questions.

**Comment by nikoladsp** [comment]
Great. Thank you kindly

**Comment by ioolkos** [comment]
> Now the first question is: can vmq_auth_acl reside in schema other than public?

Preliminary answer (without looking/research): I do not know.

> Second is: can user/pass combination be used for clients based on some pattern - like user1 with pass1 can connect to MQTT broker using any clientID in form of company1whatevertextfollows

If the question is whether you can match on some structure of the ClientID (let's say a prefix) then the answer is yes. The plugin has access to the ClientID and can do with it anything it wants. 
Multiple browser tabs for the same Client obviously is somewhat of an issue. There's no way around 1 MQTT ClientID = 1 TCP connection = 1 session/queue on the broker. You can still do it with different ClientIDs, yes (I remember some users have done this with browser tabs). What you actually might want to think about here is to cut the ClientID / Username relationship, so that you basically don't check whether a ClientID belongs to a username. (all the DB plugins in Verne check that, as it *should* be done). But the drawback of checking that is quite simply that all those ClientIDs have to be in the database. 
So I'm not really sure what the best solution is for a situation like that, but at least you should be able to figure out something workable ie good enough.

Btw, the deprecated `allow_multiple_sessions` config allowed the same ClientID to connect multiple times. It only did this on a single node, and created lots of hidden issues. Technically, it's still in, but don't use it.

**Comment by nikoladsp** [comment]
Hi,
Thank you very much on the response.

We will settle with Redis backend for now - just to evaluate VerneMQ quicker, but in the future I guess some custom plugin will do just fine. Can you please tell me if this is [good](https://github.com/vernemq/vernemq_demo_plugin) place to start with?

**Comment by ioolkos** [comment]
Demo plugin should still be fine.

There's also a Rebar3 plugin to create plugin template files:
https://github.com/redclawtech/rebar3_template_vernemq

**Comment by ioolkos** [comment]
Closing for now. Feel free to re-open or open new issue if needed.

**Comment by nikoladsp** [comment]
Thank you very much. Sorry, I forgot to close.

Best regards
