### ISSUE TITLE
Set user property and response information as part of connect ack 

### ISSUE THREAD

**Issue by nmurugesan** [vernemq/vernemq#1764]
I am trying to use Vernemq Webhook "auth_on_register_m5" to set user property and response information using modifier field. But it is not working and giving error 
is it possible to set these using webhook ?

My webhook (in python)

@api.route('/auth_on_register_m5', methods=['POST'])
def post_auth_on_register_m5():
  input = json.loads(request.data);
  print(input);

  output = {
            "result": "ok",
            "modifiers" : {
            "properties" : {
                        "p_user_property": [
                                {
                                    "key"   : "azE=",
                                    "val" : "djE="
                                }
                        ]
                     }
                }
            }

  print (output);
  return json.dumps(output)

### Environment

- VerneMQ Version: 1.9.2-1
- OS: Linux
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default  : default but vernemq webhook plugin is enabled
- Cluster size/standalone:  3 

### Expected behaviour

user property shall be set in the connect ack response

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.
New session with PID <9043.27941.1> found for client "mnallath"
<9043.27941.1> MQTT RECV: CID: "mnallath" CONNECT(c: mnallath, v: 5, u: mnallath, p: mnallath@123, cs: true, ka: 60)
    with properties: #{p_request_response_info => true,
                       p_user_property => [{<<"k1">>,<<"test">>}]}
<9043.27941.1> Calling auth_on_register_m5({{10,11,0,157},49182},{[],
                                                                  <<"mnallath">>},mnallath,mnallath@123,true)
    with properties: #{p_request_response_info => true,
                       p_user_property => [{<<"k1">>,<<"test">>}]}
=ERROR REPORT==== 31-Mar-2021::09:50:31.583374 ===
** Generic server vmq_tracer terminating
** Last message in was {trace,<9043.27941.1>,return_from,
                              {vmq_plugin,all_till_ok,2},
                              {ok,#{properties =>
                                        #{p_user_property =>
                                              [{<<"k1">>,<<"v1">>}]}}}}
** When Server state == {state,<0.63.0>,
                               {10,100},
                               <<"mnallath">>,[],200,<9043.27820.1>,
                               [{<9043.27941.1>,
                                 #Ref<9043.1769218470.304349186.197667>}],
                               undefined}
** Reason for termination ==
** {function_clause,
       [{lists,foldl,
            [#Fun<vmq_tracer.3.50438788>,[],
             #{properties => #{p_user_property => [{<<"k1">>,<<"v1">>}]}}],
            [{file,"lists.erl"},{line,1262}]},
        {vmq_tracer,format_all_till_ok_ret_,2,
            [{file,"/vernemq-build/apps/vmq_server/src/vmq_tracer.erl"},
             {line,548}]},
        {vmq_tracer,format_all_till_ok_ret,3,
            [{file,"/vernemq-build/apps/vmq_server/src/vmq_tracer.erl"},
             {line,537}]},
        {vmq_tracer,format_trace,2,
            [{file,"/vernemq-build/apps/vmq_server/src/vmq_tracer.erl"},
             {line,497}]},
        {vmq_tracer,handle_info,2,
            [{file,"/vernemq-build/apps/vmq_server/src/vmq_tracer.erl"},
             {line,219}]},
        {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
        {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

**Comment by ioolkos** [comment]
@nmurugesan this is a somewhat complex topic, apologies for only a couple of quick notes.

To see what's possible at this point, we need to separated things a little bit:

First, the MQTT packet types. See here:

https://github.com/vernemq/vernemq/blob/8c498e46fe4e017d8656cfa0533d5951ef391f09/apps/vmq_commons/src/vmq_types_mqtt5.hrl#L127
You'll see that the `?P_USER_PROPERTY_ASSOC` is missing from the `CONNACK` packet. The reason for that is that Verne is not using the `user property` to send more internal information to the client (as described by the spec).

Second, the modifiers:

They are different, per hook. They allow the plugin to override certain options. This is unrelated to what is sent back to the client, or not. That is, only because something is modified, information about that is not necessarily sent back to the client.

Third, we need to check what happens in the MQTT5 statemachine where the PACKETs are actually handled, and checked against the plugin hooks.

I only could do a quick assessment, but my take is that what you want probably does not work as is. I also thinks it's an interesting idea and use case though.

**Comment by nmurugesan** [comment]
@ioolkos  Thank you for the reply.  I want to send "subscribe-topic” as key,  user property,  to connect ack response and expecting the client to use this property to subscribe to the topic ( instead of hard coding topic to subscribe in the client side ). 

Sending user property in the connect ack response seems to be the MQTT-5 requirements (as per standard). Is there any other way i can achieve this ? 

in my setup, only vmq diversity and vmq webhook is enabled. vmq webhook is high priority and returning ok from there

**Comment by ioolkos** [comment]
> Sending user property in the connect ack response seems to be the MQTT-5 requirements (as per standard)

Just to clarify: Verne behaviour is spec conform.
The "user" in user properties is either the client or the server. The user property allows the server for the ACK-like packets to add additional information that is not semantically defined in the spec, IF it choses to do so. The other party can ignore the incoming user properties. 

Verne does not send user property in CONNACK because it does not need to send additional information in the connection setup.

Whether something like the user property is exposed to a plugin or not, again, is completely implementation dependent. I think it's a useful thing to add in a future release.

**Comment by nmurugesan** [comment]
@ioolkos  Thank you for the reply.
