### ISSUE TITLE
Changing behaviour of auth hooks processing

### ISSUE THREAD

**Issue by manifest** [vernemq/vernemq#178]
It would be nice to be able chaining auth hooks in different plugins. So that, we could reuse plugins from different authors more efficially.
For instance,
- `auth_on_register/5` hook of first plugin may perform verification of client's password.
- if there is second plugin: its `auth_on_register/5` hook may perform check of client's connections limit.
- if there is third plugin: its `auth_on_register/5` hook may create a session.
- etc.

Currently, the only way to get this behavior to add hook's success return value to plugin's settings.
It isn't useful and error prone way. It also makes developing of plugins more difficult.

The proposal to add `{next, required | optional}` return value for hooks along with `next`. It would change the processing of chain in the following way:
- `{next, optional}` - next plugin in a chain will be called until the end of the chain or `ok` value will be returned by plugin.
- `{next, required}` - just an alias for `next`, for purpose of API consistency.

**Comment by manifest** [comment]
It would be even better to pass state between plugins:
`{next, State :: any(), required | optional}`

**Comment by larshesel** [comment]
Hi @manifest, thank you for the proposal.

I've been thinking a bit about it, but as far as I can see it a hook which returns `{next, optional}` reverses the default value of the chain so the default is `ok` and not `reject` which is not desirable.

Otherwise you'd still have to make sure that the last hook knows it's the last in the chain and returns `ok` which to me seems like the same issue as we have today where you could pass `next` or `error` in each plugin until you reach the end and then decide in the last plugin if you want to return `ok` or `error`.

Regarding passing state between hooks (the same hook - not different ones) then that would certainly be possible - it's not something we currently have in the pipeline, though. It's also not clear how to make these kinds of plugins composable in a general way as the state would be different between different plugin developers.

Maybe you could show us some concrete examples where it would be a huge benefit to be able to use plugins/hooks from different authors?

A completely different way of combining hooks would be to make a wrapper plugin with a hook which calls the other hooks and handles the logic there.

Anyway, that was just my thoughts on it, let me know if there's something I misunderstood :)

**Comment by larshesel** [comment]
btw - looks like a cool couple of plugins (`vmq_tbac` and `vmq_joseauth`) you made - I suppose it's related to those you're asking these questions...

**Comment by manifest** [comment]
Hi, @larshesel! Yes, it's definitely related to plugins that I'm writing now. I've already written two that you mention, but struggle with the third.

The problems I want to solve:
1. Authenticate clients using JSON Web Tokens.
2. Light and simple authorization with rules based on topic.
3. Advanced and a bit more heavier authorization based on ACL stored in a database. There I also want to perform some per-client limit checks.

Of cause, I could implement all that logic in the huge monstrous plugin with a lot of dependencies. But it's a wrong way of doing things: it's not flexible, hard to maintain, there is zero benefit for anybody. I believe together we could make a mach better solution, and VerneMQ community would benefit from it.

I see there levels and three plugins for three problems above:
1. Authentication. `vmq_joseauth` implements authentication via JSON Web Tokens, but there could be plugin for CBOR Web Tokens, etc.
2. Stateless Authorization. `vmq_tbac` allows clients to publish and subscribe to topics that starts with their usernames. For instance, client with the username: `joe` could anytime publish and subscribe to `joe/#`.
3. Sessions. Stateful authorization. There could be a plugin that creates sessions and stores user-related data to some database, like Redis or PostgreSQL.

So that, I want to easy switch plugins making different combinations:
- JWT Authentication -> Token-Based Access Rules -> Authorization backed by Redis
- CWT Authentication -> Token-Based Access Rules
- Password Authentication -> Authorization backed by PostgreSQL
- etc.

I've thought about API a bit more and realized that better value for `{next, optional}` is `ok`, `{next, required}` is `next`, and current `ok` should be replaced by `stop`, from my point of view.
This way we could iterate through sequence, and:
- stop it as a failure, returning `{error, Reason :: any()}`
- stop it as a success, returning `stop`
- continue until we reach a right plugin's hook, returning `next`
- continue when we want to get through all the sequence of hooks and perform all the checks, returning `ok` (if there is one hook in sequence it doesn't fail execution, so that, as a plugin developer on success I can return `ok` without any knowledge of other plugins in sequence)

I attached illustrations to better understanding ideas I'm described above. You can see there, that we can't return `ok` (current `ok` that stops execution of sequence and I believe should be replaced by `stop`) because it stops execution of sequence. We can't also return `next` because it fails if there is just one plugin in sequence.

(1) Basic idea
![vmq-plugins-0](https://cloud.githubusercontent.com/assets/439058/17385956/274b0b76-59f7-11e6-9d84-8dd416af003f.png)

(2) JWT Authentication
On connection: we can only return `ok` when token has been verified and `{error, any()}` otherwise.
![vmq-plugins-1](https://cloud.githubusercontent.com/assets/439058/17386050/fc842fde-59f7-11e6-8cbd-6f5d8bf9ef4a.png)

(3) JWT Authentication -> Token-Based Access Rules.
On connection: we want two hooks get performed in sequence (authentication and authorization). On publish/subscribe: we can return `stop` when topic matches username, further processing isn't needed; `next` - for the case when topic doesn't match username; `{error, any()}` - on error.
![vmq-plugins-2](https://cloud.githubusercontent.com/assets/439058/17386292/4634d65e-59fa-11e6-9456-7164e435f4c1.png)

(4) JWT Authentication -> Token-Based Access Rules -> Authorization backed by Redis.
On connection: we want three hooks get performed in sequence.
On publish/subscribe: hooks will be reached if only access to action hasn't been granted yet.
![vmq-plugins-3](https://cloud.githubusercontent.com/assets/439058/17386333/dd3eec06-59fa-11e6-9fd3-0d3c424a14fe.png)

(5) JWT Authentication -> Authorization backed by Redis.
Here we can see, that `vmq_tbac` plugin can be easily replaced by `vmq_redisacl` plugin.
![vmq-plugins-4](https://cloud.githubusercontent.com/assets/439058/17386347/01cd1bb0-59fb-11e6-82ef-60fbac79575a.png)

**Comment by manifest** [comment]
Regarding passing state between hooks, the **state** should be represented by map. This way different plugins and their hooks would easily work with it. Plugins just need to expose some naming convention for map's keys. VerneMQ could  also specify general keys in the map.

You can see example. Same idea has been implemented for [Pragmatic Authentication Library](https://github.com/manifest/pal#authentication-schema).

**Comment by larshesel** [comment]
Ok - so I'm starting to understand this, I think.

Let me try to summarize with my own words to see if I can convey your meaning so we know if we're on the same page. The proposal would basically introduce a way to make the chain continue even when a hook has 'approved' the inputs given to it. And today that is not possible as `ok` terminates the chain and `next` will mean rejecting the connection if the hook is the last in the chain.

With the proposal we have four outcomes of a hook:

1. It can't decide what to do (next) - reject if this was the last hook.
2. This is OK - continue to next hook (ok)
3. This is OK - but stop the chain (stop)
4. Not OK - (error)

Thinking of the chain as the return values of the hooks this would mean the following values would be rejected:

[] -> reject
[next] -> reject
[error] -> reject
[..., next] -> reject
[..., error] -> reject

And the following accepted:

[ok] -> accept
[stop] -> accept
[..., ok] -> accept
[..., stop] -> accept

But in particular the following would be possible:

[next, ok] -> accept
[ok, ok] -> accept
[ok, stop] -> accept
[ok, error] -> reject
[ok, next] -> reject

Is that about it? I think it makes sense to have that extra `ok` hook that continues processing.

About passing state between the hooks I'm not yet convinced that passing a map is a good idea since it wouldn't really make the hooks composable - we could of course just ignore that and let that be a problem of the plugin developers to deal with, but that's not clear to me either that that's a good solution.

The idea of having something fixed where we expose some pre-defined keys may make sense - but it's not something we've been thinking much about until now and we'd need more data before being able to make decisions on what would be a good idea to expose for plugin developers. Remember that if we introduce this it becomes API and hard to change in the future (hence my reluctance).

I think at this point the best approach would be to store state in an ETS table or similar. I suppose some kind of lib could be developed to support this approach until to make it easier to work with.

Anyway it would be interesting to hear @dergraf 's thoughts on all this.

**Comment by manifest** [comment]
Yes, It's exactly what I meant. Thank you for making things clear.
As for the state, I don't think that map would be large enough to make a problem, when ETS table looks like a bottleneck for this case. In the mean time, I think it's a good idea to start with some library now and see what it brings to us.

**Comment by dergraf** [comment]
@larshesel I am absolutely on the same page with you here.

**Comment by larshesel** [comment]
Hi @manifest 

After having discussed the benefits of changing the hook behaviour, we've come to the conclusion that it's not something we'll be changing in the foreseeable future. The rationale is to keep the behaviour as simple and easy to understand as possible and we currently do not see a lot of requests/need for composable hooks. And if someone occasionally need to compose a couple of plugins it's still easy to accomplish this by writing a plugin wrapping the hooks.

Regarding writing a lib that makes it simple to share state between hooks/plugins we've put it into our backlog, but it's not a super high priority at the moment.

Sorry this wasn't what you were hoping for,
Lars

**Comment by manifest** [comment]
Would you mind making your decision a bit clear for me. I didn't actually catch the problems with those changes.
- If you ok with proposed changes, but don't have time to implement them. Probably, I could help and make a PR.
- If you're worry about backward compatibility with current API. We could stick to current API. It's possible to get composable hooks adding just one new possible return value for hooks (something like, `{ok, all}`, so that the full list of possible values would be `ok|{ok,all}|next|{error,any()}`).

Anyway, it could be better to have this issue open to get some feedback from developers who will look for those changes.

**Comment by manifest** [comment]
@larshesel could you please comment on my post above?

**Comment by dergraf** [comment]
Hi @manifest 

We currently support 3 different plugin chain semantics `all`, `all_till_ok`, and `only`. The relevant ones here are `all_till_ok` and `all`.

Regarding state:

The initial design goal was to allow completely different plugins to serve those hooks. It was never built to serve the composition-property. We traded composition for isolation. As a result a plugin is typically implemented as an OTP application, without any dependency to possible subsequent plugins in the chain. Passing an explicit state from one plugin to the next would weaken that isolation property. This is also the reason why a `{next, Modifiers}` does not exist btw.
If plugin composition is more valuable than isolation this could be achieved through e.g. ETS table or a nicely crafted library on top of `erlio/vmq_plugin` which we may provide in the future.

Regarding return values:

The addition of `ok_all` isn't required, as a plugin that registers e.g. `auth_on_publich` could also register `on_publish` which is called whenever `auth_on_publish`  returns `ok`.

I hope this clears things up a bit.

**Comment by manifest** [comment]
- How can I use `all` chain for `auth_on_register` hooks? Documentation said `auth_on_register` hook called as an `all_till_ok` hook. For that purpose I need the `ok_all` return value. Am I right?
- Registering `on_publish` after `auth_on_publich` require to modify plugin's source code. So that, it can't be solution in terms of independent plugins.

Without combining behaviours of `all` and `all_till_ok` chains we always be forced to write new plugins and copy-pasting logic of existed ones.

**Comment by dergraf** [comment]
@manifest, we have just seen a similar requirement in #208. I wonder if a compromise like:
`{next, Opts}` would be useful. The opts could be `any()` and only the if the plugins understand how to deal with `Opts` (e.g. they are properly ordered, from the same vendor).

What do you think?

**Comment by manifest** [comment]
@dergraf I think it would be quite useful. And it definitely solves the issue with state we talked about. Although I like the idea to use `any()` for opts (cause it provides maximum flexibility, and we shouldn't make any assumptions how plugin developers would use it), I would recommend to add a note in docs to prefer `map()` for opts, because it also makes it possible to combine plugins from different developers.

As for the case on picture 4. The case when the entire workflow is success only if all the hooks are successful (if there is any), the changes change nothing. Because `next` or `{next, any()}` would fail entire workflow when where is no "next" plugin in sequence.

**Comment by dergraf** [comment]
So for this case all but the last plugins could return  `{next, any()}` and the last one has to make sure to return `ok`. I agree this is quite cumbersome as the administrator has to double ensure the ordering is correct, however it would work ;)

**Comment by manifest** [comment]
Yes, the current workaround is to write the "special" plugin for each possible workflow and put it in the end of plugins` sequence. Or to implement wrappers for hook's return values for each "flexible" plugin (like those you can see here: [first](https://github.com/manifest/vmq_tbac/blob/master/src/vmq_tbac.erl?ts=2#L98), [second](https://github.com/manifest/vmq_tbac/blob/master/src/vmq_tbac.erl?ts=2#L111) and [third](https://github.com/manifest/vmq_tbac/blob/master/src/vmq_tbac.erl?ts=2#L121)). Both workarounds are kind of ugly and make dynamic plugin system useless. Kind of pain for plugin developer, I could say.

**Comment by dergraf** [comment]
I wouldn't say it make dynamic plugin system useless, we've implemented e.g. `vmq_diversity` and `vmq_webhooks` using the exact same plugin system, and I think they are highly dynamic and generic. I understand your critic though that plugin composition could be better, hence enabling more flexible plugin chains. The mentioned PR would IMO heavily improve on that. 

Regarding one of your other points,  the ability to use `next` to terminate an `all_till_ok` plugin chain with success instead of a failure is rather a philosophical discussion. VerneMQ follows the Unix approach when it comes to authentication and authorization. E.g. in contrast to other brokers we don't allow anonymous clients per default, and therefore always require an authentication plugin (defaults to `vmq_passwd`) and an authorization plugin (defaults to `vmq_acl`) to be installed. We know that this doesn't necessarily lower the barrier for newcomers, but it is a trade-off we think we have to take. 

Of course we could add more configuration to the plugin system, enabling to further specify the behaviour of the different chains. However, if you have a look at the plugin system you can see that it is built for performance, e.g. not a single ETS lookup is required to iterate through a chain, as a chain is a dynamically compiled Erlang module. As we are not fans of this kind of meta-programming voodoo in Erlang, we want to keep it as low profile as possible ;) Therefore, wherever we required more control over the chains, as in `vmq_webhook` or `vmq_diversity` we took another route and implemented a plugin layer on top of our internal plugin mechanism (see https://github.com/erlio/vmq_webhooks/blob/master/src/vmq_webhooks_plugin.erl#L220-L248). 
We prefer that plugins that are of such a dynamic nature should follow a similar approach.
I hope this all makes sense. 

BTW: your `vmq_tbac` plugin uses a call to `application:get_env` at very delicate positions which becomes a bottleneck. You should avoid `application:get_env` in your fast path.

**Comment by manifest** [comment]
Yes, changes within that mentioned PR will definitely make plugin system more flexible. And I believe it could be even more flexible than that if we make a move from the "put all plugins into the one" approach you're talking about. I called dynamic plugin system useless because of that approach. Talking about `vmq_diversity` and `vmq_webhooks`, there are no plugins - just one.
- If there is only one plugin possible, what the difference between starting/stopping plugin and starting/stopping entire broker? Can we call this "plugin" system or use word "dynamic" with it?
- What the purpose of returning `next` from hooks?
We have only one plugin in that approach. There is not match sense in `vmq-admin plugin enable ...` or any other `vmq-admin plugin` CLI commands. it's a pity.

As for Unix philosophy, I believe we could stick to it, and have a better plugin system in the same time. I mean, we could check how many hooks (functions to call) are passed to `vmq_plugin:all_till_ok/2`. If there none - we fail. This way, we don't need to rely on return values of plugins` hooks.

As for bottleneck with `application:get_env`, you're right. It's similar to one (single ETS table) that is used in both of `vmq_diversity` and `vmq_webhooks` plugins. I would like to throw away those hacks, but can't because of limitations of plugin system. That is the main reason why this issue was opened.

**Comment by larshesel** [comment]
Closing this until we start work on VerneMQ 2.0.
