### ISSUE TITLE
Unable to get VerneMQ configured with SSL

### ISSUE THREAD

**Issue by nsnavare** [vernemq/vernemq#1784]
Hello, I want to configure VerneMQ to work over WebSockets and standard SSL connections. The vernemq.conf file is zipped and 
[vernemq.conf.zip](https://github.com/vernemq/vernemq/files/6369760/vernemq.conf.zip)
attached for reference.

However, when I try to use mosquitto_sub, I get an error saying that a TLS error occured. Also, when I try to connect through websockets using the simple websocket client extension in chrome, I get a message saying "Undefined".

I am using a DigitalOcean droplet with LetsEncrypt certificates for my domain enscloud.in.

Please guide.

**Comment by ioolkos** [comment]
@nsnavare first, determine which listeners are actually running, by `vmq-admin listener show`.
Then try switching all configs to a named listener configuration instead of protocol level configs. (this means you'd take the defined listener name, and add it to the config values for example where you configure the SSL cert files).
