### ISSUE TITLE
username not present in the on_client_gone and on_client_offline webhooks

### ISSUE THREAD

**Issue by dumbpreacher** [vernemq/vernemq#1798]
The webhook bodies for on_client_gone and on_client_offline do not contain username field. I would like some context around why this decision was taken and if adding it would cause some unwanted effects

**Comment by ioolkos** [comment]
@dumbpreacher mainly because the ClientID is guaranteed to be unique not the Username. When multiple MQTT clients are using the same Username, the information isn't that useful.

**Comment by dumbpreacher** [comment]
@ioolkos thanks a lot for the quick response. But I have a doubt around why some webhooks contain the username and some don't (specifically the ones that are called when the client disconnects). Is this intentional? If I add the username in the on_client_offline or on_client_gone for my specific usecase, will it cause any side effects in the desired behavious?

**Comment by ioolkos** [comment]
@dumbpreacher decisions like that are a balance between what you can do and should do. We could obviously add everything to hooks with the philosophy that someone might have a use case. OTOH all the other use cases will see increased payload sizes, traffic etc.

For your specific question: why not just test it instead of me having to think and "guarantee" that there will be no side-effects :)

**Comment by dumbpreacher** [comment]
Thanks @ioolkos, will test this and get back.
