### ISSUE TITLE
a question of offline storage

### ISSUE THREAD

**Issue by lizhe19** [vernemq/vernemq#1916]
when I set max_offline_messages = -1, and Producers keep producing new messages but have no consumers or consumer offline, how does levelDB do? and when the disk takes up more and more space, how do i do?

**Comment by ioolkos** [comment]
The offline consumer queues will fill up without any bound (supposing the consumers are persistent consumers). That's why there's a configurable limit to protect system resources.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by lizhe19** [comment]
你好...谢谢你的邮件 我已收到！

**Comment by lizhe19** [comment]
thank u. i gei it
