### ISSUE TITLE
some question about client connect

### ISSUE THREAD

**Issue by lizhe19** [vernemq/vernemq#1922]
1.The retain parameter is not valid for shared subscriptions?
2.What is the maximum number of online clients? Are there any parameters that can be configured?
3.I use Mysql to control the permission of topic publishing and subscription. When the client is connected online, I modify vmq_auth_acl publish_acl and subscribe_acl, current client The publish and subscription does not take effect. When the client reconnects, the publish subscription takes effect. Cannot load permissions dynamically。

**Comment by lizhe19** [comment]
question3 detail:
1.the client has topic2`s pub and sub permission
![image](https://user-images.githubusercontent.com/30067432/146912772-6645b91c-8793-41b3-89a1-53ba28c0cde4.png)

2.vmq_auth_acl`s publish_acl and subscribe_acl add topic3.

3.the client is keep online, but can not sub and pub 
![image](https://user-images.githubusercontent.com/30067432/146912806-1b378837-1638-43b3-a8f4-8d040c963a21.png)

4.when I reconnect the cient , I can pub and sub.
![image](https://user-images.githubusercontent.com/30067432/146912837-0afc5f9d-7671-47a0-8c88-782cad3a75db.png)

**Comment by lizhe19** [comment]
Cannot load permissions dynamically。

**Comment by ioolkos** [comment]
> 1.The retain parameter is not valid for shared subscriptions? 

I believe retained messages are not delivered to not interfere with load balancing. I have not looked at the code to verify this, right now.

> 2.What is the maximum number of online clients? Are there any parameters that can be configured? 

There is no artificial max number. Of course, there are params that need to be configured. Please refer to the documentation.

> 3.I use Mysql to control the permission of topic publishing and subscription. When the client is connected online, I modify vmq_auth_acl publish_acl and subscribe_acl, current client The publish and subscription does not take effect. When the client reconnects, the publish subscription takes effect. Cannot load permissions dynamically。

That is correct, since ACLs are cached in the session during CONNECT. This will currently only update/invalidate the cache when the client re-connects.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by lizhe19** [comment]
Q1:
retain for shared subscriptions has any mqtt5 protocols standard？and thank u for confirm the Q1 .
Q2:
which params can i conf？i cant find it
Q3:
very thank u. i get i

**Comment by lizhe19** [comment]
@ioolkos
