### ISSUE TITLE
Question: vernemq 1.12.4

### ISSUE THREAD

**Issue by rotarur** [vernemq/vernemq#1948]
Why there is no docker image of vernemq 1.12.4 till now ? This version was released in december and there is no image created in docker hub. Are you planning to move out from docker hub?

**Comment by ioolkos** [comment]
@rotarur 1.12.4 will be superseded shortly because it needs dependency updates. On your second question, I'm pondering options.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription
