### ISSUE TITLE
Distribution of messages among offline clients

### ISSUE THREAD

**Issue by mwilniewiec** [vernemq/vernemq#1958]
- VerneMQ Version: 1.12.3
- OS: Ubuntu 18
- Cluster size/standalone: 1

I was testing shared subscriptions and I found one issue that can be problematic for unaware users and I think this could be fixed.
Consider a case where horizontally scaled microservice subscribes to a topic using a shared subscription (for load balancing).
Steps:
1. 5 Instances of a service are subscribed to a shared topic using QOS=1 & clean=false wanting not to lose messages
2. Services get messages distributed among 5 instances **OK**
3. Autoscaler or admin scales microservice to 1
4. Only one online microservice is receiving all the messages now **OK**
5. Microservice dies because of any reason
6. Messages are distributed among 5 offline clients **NOK** & VerneMQ is waiting for those clients to connect
7. Died microservice is stared again and gets 1/5 of messages (published during offline period) **NOK**
8. 4/5 of messages will be published to other subscribers when they connect (if it ever happens) **NOK**

Expected:
In my opinion when all subscribers are offline, qos 1 messages should be treated equally an no client assignment should be done. Client assignment should be done just before sending messages to online clients, not before saving msgs to DB.
With such implementation first client becoming online would receive all messages from the offline period and no msgs would be lost or processed later than expected.

**Comment by ioolkos** [comment]
@mwilniewiec Thank you for your input. It's an often raised point.

While I do not dismiss it as invalid, your picture of the feature is incomplete. Let me, therefore, add a couple of points.

You expect Shared subscriptions to behave as a single queue. This is not the case in VerneMQ. Each subscriber has an exclusive queue it consumes from. This enables the following features:

1. Shared consumers can still control their session settings (like a regular MQTT client). Namely, they should not request message persistence if they do not intend to come back to collect them.
3. Mixed scenarios (some subscribers are persistent, some not)
4. Optimisation in a cluster: we can deliver messages incoming at a specific node to a shared subscriber on that same node. This is called `local` delivery.
5. Above allows for more flexible load balancing policies (called `Shared Subscription Policies`). Currently, the following policies are implemented:  `prefer_local`, `local_only`, `random`, and `prefer_online_to_local`. The last one is new and available in the main branch but not yet part of a release.

So there are multiple criteria in a `Shared Subscription Policy`. Some of those are implicit and admittedly non-intuitive. (`prefer_local` will prefer an offline consumer on the local node to an online consumer at a different node, as an example).
To make things simpler, I have added the `prefer_online_to_local` strategy, which always routes messages to an (any) online consumer in the cluster. It's a more expensive strategy because we need to determine whether consumers are online or offline. But it might be an acceptable trade-off for your use case, as it should allow you to avoid "cold" offline queues.

On a general note: you can use Shared subscribers to do consumer side load-balancing. So you'd use five subscribers when the capacity of your consuming application allows for 1/5 of the message throughput. If one consumer can handle it all, why use Shared Subscribers at all? (rhetorical point only... I get what you want to do)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mwilniewiec** [comment]
I came here with quite good knowledge on how RabbitMQ or Kafka works. Maybe I'm a bit shortsighted when it comes to MQTT but lets take the problem under consideration starting from the very beginning.

What was the real motivation of introducing shared subscriptions in MQTT?
I would say this is **load balancing of messages between multiple customers**.
Why would you ever want to load balance your messages?
1. Thoughtput is so big that vertical scaling of a customer is not enough, you want to scale horizontaly.
2. You want to have high availability of your consumer and when one dies you want others to do his job immediately.
3. Your thoughtput is not that big right now but you are building a horizotally scallable system which is able to handle lots of users/iot devices and get ready for the future.
Additionally new trends like microservices, kubernetes/docker swarm, autoscaling makes it very simple to scale up your services to have multiple consumers.
I would say that vast majority of shared subscription clients are horizontally scaled services (where every each of it is the same, in rare cases twin-similar). Its designed for a many publishers, one subscriber problem.

What was the real motivation of doing clustering in VerneMQ?
I would say 3 points from above are also valid. 
I also think that broker cluster should give you those benefits but should be totally transparent when it comes to functionality and how clients use the broker. When you a are a publisher or a subscriber you don't care if broker is a single instance or its a cluster of 10.

I can understand that current implementation works the way you described but its a bit hard for me to find a business case where multiple consumers sharing one subscription are set in a mixed mode where some are persistent, some are not. 
A consumer using a shared subscription will get only a random part of the whole stream. When he is really unlucky, he might get almost no messages.
I can't also find a business case where online client is doing nothing and messages are sent to a local offline client queue and waiting for him to connect (if it ever happens).
Of course in case clients configure such a monster - broker must behave somehow but I would say its a minor problem how it's solved.

My thoughts:
The tool/feature/program should mainly solve the problem it is created for. Implementation under the hood is just a detail.
If only motivation of `Shared Subscription Policies` was performance optimization I would say its unnecessary complexity and it breaks the rule of standalone broker working the same as cluster of brokers.

From my perspective the basic rule for Shared subscriptions should be `Distribute between online clients`.
With optional settings like: `random_local_first`, `random`, `round_robin`, `idle_first`.
