### ISSUE TITLE
Huge delay for on_publish webhook

### ISSUE THREAD

**Issue by mulsen** [vernemq/vernemq#1977]
Hi,
we are experimenting with vernemq and the on_publish webhook. Basically, on every on_publish an insert to a postgres database should happen. Both, vernemq and postgres are on the same server. The mqtt messages come from another machine. For testing we sent 1,000 mqtt messages to vernemq. All 1,000 messages are sent within ~1sec. On vernemq we experienced a delay in the processing of the requests (delay in calling the lua script on_publish). Basically the first time the lua script is called is ~3sec after we sent a request to vernemq. Of course there is a delay to vernemq from the machine we sent the mqtt requests, but it is not 3sec.

In general we get the following delays:

| Request number      | on_publish lua script  started| lua script duration|
| ----------- | ----------- |----------- |
| 1      | ~3sec delay|0.007sec
| 2        |~3sec delay|0.004sec
| ...| ...|...|
| 100        |~4sec delay|0.28sec
| ...| ...|...|
| 500        |~15sec delay|0.15sec
| ...| ...|...|
| 800        |~21sec delay|0.21sec
| ...| ...|...|
| 1000        | ~23sec delay|0.05sec

Why are these delays that high? 

### Environment

- VerneMQ Version: latest (1.12.4) 
- OS: Linux
- Erlang/OTP version (if building from source): docker image
- VerneMQ configuration (vernemq.conf) or the changes from the default: no changes
- Cluster size/standalone: standalone

### Expected behaviour

We would expect no or smaller delays for calling the on_publish method.

### Actual behaviour

Huge delays for the on_publish method.

**Comment by ioolkos** [comment]
> Why are these delays that high?

I don't know. Have you experimented with setting a different or higher `vmq_webhooks.pool_max_connections`?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mulsen** [comment]
I tried to increase the `vmq_webhooks.pool_max_connections` value. Still the same issue. But generally, VerneMQ should be able to handle huge loads, right? So it must be a configuration issue somewhere.

**Comment by ioolkos** [comment]
Note: issue opener titled this as `WebHooks` issue but is describing an issue with an adapted Lua script. So my initial recommendations are irrelevant, apologies.
Notification hooks should be processed concurrently, that is return immediately and do the processing in another thread. I recently discovered this with the `on_publish` WebHook. If the WebHook implementation accumulates delays by working sequentially and increased delays (due to some processing like writing to a DB), this is possibly going to affect VerneMQ.
I suspect the same might apply to processing in a Lua script.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
