### ISSUE TITLE
QoS behavior bis

### ISSUE THREAD

**Issue by dometec** [vernemq/vernemq#1982]
### Environment

- VerneMQ Version: 1.12.3 (docker)
- OS: Fedora
- VerneMQ configuration (vernemq.conf) or the changes from the default: Set only ACCEPT_EULA / ALLOW_ANONYMOUS / UPGRADE_OUTGOING_QOS
- Cluster size/standalone: standalone

### Expected behaviour

I test locally the behaviour of VerneMQ using mosquitto clients when subscriber and publisher are using different QoS level.
What I'm expecting is resumed in "**3.8.4 Response**" in "**Non normative examples**" and "**Non normative comment**" of http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html: 

_Subscribing to a Topic Filter at QoS 2 is equivalent to saying "I would like to receive Messages matching this filter at the QoS with which they were published". This means a publisher is responsible for determining the maximum QoS a Message can be delivered at, but a subscriber is able to require that the Server downgrades the QoS to one more suitable for its usage._

So, I starter a new VerneMQ standalone server with:

`docker run --rm -it -p 1883:1883 -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" -e "DOCKER_VERNEMQ_UPGRADE_OUTGOING_QOS=off" --name vernemq vernemq/vernemq:1.12.3`

Subscribe with mosquitto_sub to a topic qith QoS 2:

> [dometec@localhost ~]$ mosquitto_sub -d -q 2 -t 'topic1'
> Client null sending CONNECT
> Client null received CONNACK (0)
> Client null sending SUBSCRIBE (Mid: 1, Topic: topic1, QoS: 2, Options: 0x00)
> Client null received SUBACK
> Subscribed (mid: 1): 2

And publish a message with QoS 1:

> [dometec@localhost ~]$ mosquitto_pub -d -t 'topic1' -m 'ciao' -q 1
> Client null sending CONNECT
> Client null received CONNACK (0)
> Client null sending PUBLISH (d0, q1, r0, m1, 'topic1', ... (4 bytes))
> Client null received PUBACK (Mid: 1, RC:0)
> Client null sending DISCONNECT
> [dometec@localhost ~]$

Following the specification, I would aspect on subscriber a message with QoS 1.

### Actual behaviour

I get a message with QoS 2:

> Client null received PUBLISH (d0, **q2**, r0, m1, 'topic1', ... (4 bytes))
> Client null sending PUBREC (m1, rc0)
> Client null received PUBREL (Mid: 1)
> Client null sending PUBCOMP (m1)
> ciao

The same if I send a message with QoS 1 (always received a QoS 2 message).

I tested this scenario with a Mosquitto Server and it follows the specification.

I think this issue is related to #741, it seems that the variable UPGRADE_OUTGOING_QOS is always on regardless of the value that I assign to it.

Thanks
Domenico

**Comment by ioolkos** [comment]
@dometec thanks, ups did we break the spec again? :)

Seriously, though, I think we implemented it looking at it from the other side, instead of downgrading the consumer, we "upgrade" to what the publisher says. Which should be the same, but maybe we missed a thing. (for instance not downgrade when Consumer QoS > Publisher QoS).
Specifically, what behaviour do you see when `upgrade_outgoing_qos` is on?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by dometec** [comment]
Thanks, @ioolkos, I don't notice any changes.

However, I see others have interpreted the specs in this way, for example (see the Note): https://subscription.packtpub.com/book/application_development/9781787287815/1/ch01lvl1sec19/learning-about-the-different-quality-of-service-levels

**Comment by ioolkos** [comment]
@dometec the spec non-normatively but nevertheless clearly seems to state this, yes.
Never seen any problems with the way Verne implements this. Still will have to look into this and decide whether to adapt behaviour.
Thanks!

----
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
Additional context: I think we originally had a wrong understanding for this, and it got never corrected.
In short, we implemented a configurable upgrade of the Subscriber QoS to the Publisher QoS. If off, the Subscriber QoS would always stay at the configured QoS level.

The spec says to use the Publisher QoS as a default for the Subscriber QoS (within the configured Subscriber QoS as "highest" QoS to be accepted). The configurable "upgrade" then should upgrade to the Subscriber QoS, not the Publisher QoS.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by aoiremax** [comment]
@ioolkos I'm not sure that you've got exactly the point. It's not a matter of downgrading or upgrading neither the Subscriber QoS nor the Publisher QoS. It's about selection of QoS that the **Server** has to use to deliver a message to a subscribed **Client**. And mandatory statement **[MQTT-3.8.4-6]** in [section 3.8.4 of MQTT v3.1.1](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718067) specification is really clear about this:

`The Server might grant a lower maximum QoS than the subscriber requested. The QoS of Payload Messages sent in response to a Subscription MUST be the minimum of the QoS of the originally published message and the maximum QoS granted by the Server.`

Therefore, Server default behaviour MUST be the specified one, using the minimum.

If you would like a non-standard option that forces the Server to always use the Subscriber QoS (or, better, the maximum QoS the Server has granted to the Subscriber), I would not call it _upgrade_outgoing_qos_ as it is misleading due to the fact that in some cases it is not upgrading but downgrading message QoS.

Looking at next [piece of code in vmq_server/src/vmq_mqtt_fsm.erl](https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_mqtt_fsm.erl#L1034), comment seems OK, but about Erlang implementation I do not know enough:

> %% The MQTT specification requires that the QoS of a message delivered to a
%% subscriber is never upgraded to match the QoS of the subscription. If
%% upgrade_outgoing_qos is set true, messages sent to a subscriber will always
%% match the QoS of its subscription. This is a non-standard option not provided
%% for by the spec.
-spec maybe_upgrade_qos(qos(), qos(),state()) -> qos().
maybe_upgrade_qos(SubQoS, PubQoS, _) when SubQoS =< PubQoS ->
    %% already ref counted in vmq_reg
    SubQoS;
maybe_upgrade_qos(SubQoS, PubQoS, #state{upgrade_qos=true}) when SubQoS > PubQoS ->
    %% already ref counted in vmq_reg
    SubQoS;
maybe_upgrade_qos(_, PubQoS, _) ->
    %% matches when PubQoS is smaller than SubQoS and upgrade_qos=false
    %% SubQoS = 0, PubQoS cannot be smaller than 0, --> matched in first case
    %% SubQoS = 1|2, PubQoS = 0 ---> this case
    PubQoS.
