### ISSUE TITLE
Sticky shared subscriptions

### ISSUE THREAD

**Issue by lasfromhell** [vernemq/vernemq#2019]
We are using shared subscriptions to handle messages on multiple instances of mqtt client application. To distribute messages we're subscribing to topics with name like '$shared/GRP/a/b/+/+/c/d'. In this situation with existing distribution policies we have no guarantees that the same instance of client application (the same subscriber) will handle messages from the same topic which breaks ordering of message handling.

It'd be nice to have support of sticky shared subscriptions like here - https://flespi.com/blog/sticky-shared-subscriptions-smarter-load-balancing-with-flespi-mqtt-broker or to have a 'hash' distribution policy like here - https://www.emqx.io/docs/en/v5.0/advanced/shared-subscriptions.html#load-balancing-policy-and-dispatch-ack-configuration.

Or may be it's already possible to achieve this goal somehow using existing vernemq?

**Comment by ioolkos** [comment]
@lasfromhell Verne implements shared subscription policies based on the assumption that the way to optimise delivery is to take into account to which node the PUBLISHER of the message is connected to. Verne can then deliver this message to a SUBSCRIBER connected to the same node, so that no in-cluster communication is needed. This is what `local` means. I don't know whether we can call this a variant of 'stickyness'.

There's also the built-in assumption that you prefer to deliver to an `online` queue before an `offline` queue. This is the weaker of the 2 assumptions, that is the `local` one sets the boundaries. Therefore, you can reverse the order with the `prefer_online_before_local` configuration, which is probably the most intuitive one. It will look for an online subscriber on a non-local node, if there are only offline subscribers on the local one.

- random, 
- prefer_local,
- local_only,
- prefer_online_before_local

Whether one of those policies matches your needs is for you to decide, of course.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by lasfromhell** [comment]
Yes, I understand `local` policies but in this case Verne sends the message to a random subscriber connected to local node (node the publisher of the message is connected to). But in our situation we need guarantees that the same subscriber will be selected for the same publisher (or for the same topic name), need to be sure that messages from the same topic always handled by the same application instance (subscription with wildcards, so each instance is subscribed to multiple topics)

**Comment by lasfromhell** [comment]
Is it possible to implement in plug-in? I see there hooks like 'on_publish' and 'on_deliver' but looks like that these hooks don't allow to select another subscriber.

**Comment by ioolkos** [comment]
No, it can't be done as a plug-in. It needs to be added as a shared subscriber policy. The filter here does not have access to the publishing ClientId, though (supposing you'd want to hash on it); it would've to be injected from upstream calls.

https://github.com/vernemq/vernemq/blob/f08eb1405d781374bd99999068ac8f276d56fbd9/apps/vmq_server/src/vmq_shared_subscriptions.erl#L106

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by lasfromhell** [comment]
Okay, thank you for details

**Comment by Climax777** [comment]
Why was this closed? I require something similar. Order of messages are important in my use case, and randomly distributing messages will break this. Hash-based routing is essential

**Comment by ioolkos** [comment]
@Climax777 Issue is closed because I took the time to layout what is implemented and what is currently not implemented. I also gave hints on how to go about it if someone needs to add this.
I'll happily review any related PRs!

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
