### ISSUE TITLE
1.12.6.2 a ssl listener setup

### ISSUE THREAD

**Issue by ioolkos** [vernemq/vernemq#2068]
No, it does not solve the mqtts problem. In 1.12.6.2 a ssl connect looks like this:

```
❯ openssl s_client -port 8883 -host mqtt.localdomain
CONNECTED(00000005)
4380345900:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/libressl/libressl-2.8/ssl/ssl_pkt.c:585:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Start Time: 1672347400
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
```

but it should look look like this:

```
❯ openssl s_client -port 8883 -host mqtt.localdomain
CONNECTED(00000005)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = mqtt.localdomain
verify return:1
---
Certificate chain
 0 s:/CN=mqtt.localdomain
   i:/C=US/O=Let's Encrypt/CN=R3
 1 s:/C=US/O=Let's Encrypt/CN=R3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
 2 s:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
[....]
-----END CERTIFICATE-----
subject=/CN=mqtt.localdomain
issuer=/C=US/O=Let's Encrypt/CN=R3
---
No client certificate CA names sent
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4515 bytes and written 322 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 81497B9CB586F8822E600B8B95BA51FAFD766EAAEF2D6AC8017AED53B3EABD3B
    Session-ID-ctx:
    Master-Key: CF45890E1887C98A883AE7C282DB43F7CEF897C76BEDC97C8ADC9C51C279C716C88F31A5AF0B348F59DB607F838DA432
    Start Time: 1672347777
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
quit
closed
```

Config is 100% the same.
SSL certificates are configured like shown above using env vars.

1.12.6.2 does load the certificates correctly!?

_Originally posted by @kettenbach-it in https://github.com/vernemq/vernemq/issues/2061#issuecomment-1367585244_

**Comment by codeadict** [comment]
Looks like the first one was compiled in OSX with Apple LibreSSL?

**Comment by sivaNbalusu5** [comment]
I have the same issue:

have deployed to k8s cluster using helm chart, pod started fine and conf looks like this:
########## Start ##########
allow_register_during_netsplit=on
allow_unsubscribe_during_netsplit=on
accept_eula=yes
allow_publish_during_netsplit=on
listener.ssl.default=[0.0.0.0:8883](http://0.0.0.0:8883/)
listener.ssl.keyfile=/etc/ssl/vernemq/tls.key
listener.ssl.cafile=/etc/ssl/vernemq/ca.crt
listener.tcp.localhost=[127.0.0.1:1883](http://127.0.0.1:1883/)
allow_anonymous=on
listener.ssl.certfile=/etc/ssl/vernemq/tls.crt
allow_subscribe_during_netsplit=on
listener.tcp.default = [10.105.0.86:1883](http://10.105.0.86:1883/)
listener.ws.default = [10.105.0.86:8080](http://10.105.0.86:8080/)
listener.vmq.clustering = [10.105.0.86:44053](http://10.105.0.86:44053/)
listener.http.metrics = [10.105.0.86:8888](http://10.105.0.86:8888/)
########## End ##########



but pod logs shows this error:

20:13:35.558 [error] can't reconfigure mqtts listener({127,0,0,1}, 1883) with Options [{max_connections,10000},{nr_of_acceptors,10},{mountpoint,[]},{cafile,"/etc/ssl/vernemq/ca.crt"},{depth,1},{certfile,"/etc/ssl/vernemq/tls.crt"},{eccs,[sect571r1,sect571k1,secp521r1,brainpoolP512r1,sect409k1,sect409r1,brainpoolP384r1,secp384r1,sect283k1,sect283r1,brainpoolP256r1,secp256k1,secp256r1,sect239k1,sect233k1,sect233r1,secp224k1,secp224r1,sect193r1,sect193r2,secp192k1,secp192r1,sect163k1,sect163r1,sect163r2,secp160k1,secp160r1,secp160r2]},{keyfile,"/etc/ssl/vernemq/tls.key"},{require_certificate,false},{tls_version,'tlsv1.2'},{use_identity_as_username,false},{allowed_protocol_versions,[3,4,131]},{allow_anonymous_override,false}] due to {already_started,<0.461.0>}


I tried using " openssl s_client -connect :8883 -key tls.key.pem -cert tls.cert.pem", got back the info below.

CONNECTED(00000003) 
write:errno=54 
--- no peer certificate available 
--- No client certificate CA names sent
 --- SSL handshake has read 0 bytes and written 287 bytes 
--- New, (NONE), Cipher is (NONE) Secure Renegotiation IS NOT supported Compression: NONE Expansion: NONE No ALPN negotiated SSL-Session: Protocol : TLSv1.3 Cipher : 0000 Session-ID: Session-ID-ctx: Master-Key: Start Time: 1670975815 Timeout : 7200 (sec) Verify return code: 0 (ok)

**Comment by sivaNbalusu5** [comment]
@ioolkos were you able to figure out the root cause. If so could you please post the update here

**Comment by ioolkos** [comment]
@sivaNbalusu5 
as a general rule I recommend to use "named" configurations, as in the following example (with listener name "default")

```
listener.ssl.default=0.0.0.0:8883
listener.ssl.default.keyfile=/etc/ssl/vernemq/tls.key
listener.ssl.default.cafile=/etc/ssl/vernemq/ca.crt
listener.ssl.default.certfile=/etc/ssl/vernemq/tls.crt
```

Also, your OpenSSL call is wrong as you don't want to give client cert and key. (you do not require a client cert from the broker side).

Try a call like `openssl s_client -connect localhost:8883` first.

The logged error about listener reconfiguration is a minor issue but not related. (it's related to default listeners given; will fix this)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
For MQTTS listeners in Docker images, notice this. 
https://erlangforums.com/t/latest-vernemq-not-allowing-tls-traffic-with-self-signed-ca-certificate/2394/11?u=afa

A lot, if not most of the SSL issues in the Docker image come from the configuration of the path to the CAfile.

If the 'default' listener name creates clashes, use different listener names for the listeners you'd like to configure. (example `listener.tcp.my_listener = 127.0.0.1:1883`)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
The listener error is fixed by: https://github.com/vernemq/vernemq/pull/2113

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
