### ISSUE TITLE
Error adding node to cluster

### ISSUE THREAD

**Issue by diogoaraujodtx** [vernemq/vernemq#2328]
I ran **./vmq-admin cluster join discovery-node=<node_ip>** to add the current node to a cluster. It retrieves **RPC to node <node_ip> failed for reason: non_empty_node**. Can someone help me?

**Comment by ioolkos** [comment]
Release 2.0.0+ has a new setting: `vmq_swc.prevent_nonempty_join` which is `on` by default.
You can set it to `off` for backward compatibility.

But note: the point of  this is to prevent nodes with pre-existing history from joining a cluster. The setting triggers a self-check on the node that wants to join the cluster, and then prevents it from joining if it finds existing history. With existing history, metadata synchronization is not guaranteed to work (but *might* work, partially or fully).

existing history = all events on the broker before it gets clustered. An event could be an MQTT client registering on the broker.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by diogoaraujodtx** [comment]
I am using this git repository to deploy VerneMQ. Is this new setting active here?

**Comment by ioolkos** [comment]
Yes

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
If this is a bit confusing, here's more info.

In your release, you'll have a data directory with the following directories:

- broker
- generated.configs
- msgstore
- swc_meta

The history (= state) that is relevant for the self-check is metadata (mainly subscriptions). This is stored on disk in `swc_meta`. If an MQTT client connects and subscribes to a topic (as an example), `swc_meta` will be populated and prevent itself from joining a cluster.

To reset a node, it needs to be stopped and `swc_meta` needs to be renamed or deleted.
Then you can reboot the node, and the boot will create a new `swc_meta` directory. 

Since you can only cluster a node when it is started, you will have an independent (=non-clustered) VerneMQ node running before you issue the cluster command. Within that time window (boot to clustering), you need to keep the node "protected" from MQTT clients.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
