### ISSUE TITLE
Webhook error behaviour on connection errors

### ISSUE THREAD

**Issue by baranga** [vernemq/vernemq#737]
### Environment

- VerneMQ Version: 1.3.1
- OS: Debian

In my current setup I use a combination of vmq_webhooks and vmq_pwd/vmq_acl to handle authentication and authorization. Regular users will be handled by the webhooks and system users will be handled by the configured credentials.

### Expected behavior

I can configure per webhook if a connection error leads to a `error` or `next` result. With this I can establish a line of last resort with some credentials I can rely on, event if preceding webhooks fail.

### Actual behaviour

Right now a connection error on a webhook will break the plugin chain. In my case that means if the web app is down (restart due upgrade or crash) non of my system users can connect.

**Comment by larshesel** [comment]
Hi, that's a thing I don't think we ever considered - by default we treat errors as errors and break the chain and thus lean towards the secure side - no nasty surprises because something didn't work as expected. I think that's how it should be - but I guess an option could be added to somehow decide what the plugin should do in such cases - the default could still be error, but it could be possible to override the value to `next`.
