### ISSUE TITLE
Prefix trace output with timestamp

### ISSUE THREAD

**Issue by chriswue** [vernemq/vernemq#782]
While investigating #768 I used the trace feature which is quite cool. But it would be even more useful if the trace output could be prefixed with the timestamp. Otherwise it can be a bit difficult to reason about exact timelines involving timeouts, etc. after the fact.

**Comment by larshesel** [comment]
Hi, this is a great idea which we also thought about while building the tracing system. We didn't add this then since you can pipe the output to the `ts` command which prefixes all lines piped to it with a timestamp (or incremental time) and we wanted to keep the implementation as simple as possible. Of course not everyone know this trick, and therefore I think adding timestamps is something we should add at sometime in the future. We have a rework of the tracing feature on the backlog where we'll make it multi-node - that might be a good point to add timestamps as well.

**Comment by dambrisco** [comment]
This feature's value is increased in container-based environments.

For example, if you're administering a kubernetes-based cluster from an OS X machine, you would need to install `ts` via brew or elsewhere. Even if you have it installed, however, logging from kubernetes is not immediate and is, to some extent, reliant on your network's reliability, so it's entirely possible to end up with timestamps that aren't actually representative of the timings within VMQ. In turn, this misrepresentation can easily disguise timeout-related issues that would otherwise be more obvious with timestamps generated within the trace itself.e

**Comment by codeadict** [comment]
What is the preferred format for these timestamps? Any idea @ioolkos ? I have it working in a branch of mine, thinking about using UTC like:

<img width="1021" alt="Screen Shot 2020-04-27 at 5 50 42 PM" src="https://user-images.githubusercontent.com/168440/80424417-aceba480-88af-11ea-8b79-28910ddee026.png">

**Comment by chriswue** [comment]
I'd prefer ISO8601 format, UTC or local doesn't matter so much as the timezone offset is correctly included.

**Comment by codeadict** [comment]
Thanks @chriswue, that makes sense. I'll hear more input and decide for a format.

**Comment by ioolkos** [comment]
I think I'm fine with anything proposed here. As long as we don't need a third party dependency for it! :)

**Comment by codeadict** [comment]
Yeah no third parties. I hand crafted the function for it :). PR comming later today.

**Comment by codeadict** [comment]
Looks like this can be closed now @ioolkos
