### ISSUE TITLE
leveldb performance revisted 

### ISSUE THREAD

**Issue by chriswue** [vernemq/vernemq#886]
- VerneMQ Version: 1.5.0
- OS: running in docker on Ubuntu 18.04

This is related to #771. We've been revisiting the use of the leveldb backend again since it would provide us with some persistence guarantees against unexpected outages. Unfortunately the current problem is that publishers can outperform subscribers by more than a factor of 2 ultimately leading to overflowing queues and dropped messages.

The way it look like to me from the outside is:
* vernemq receives a QoS1 PUB
* vernemq submits the message to the leveldb backend and immediately replies with a PUBACK
* Only once the write has been committed to leveldb will the subscribers actually get the message delivered

If this is approximately what happens then can vernemq be changed so it only sends the PUBACK once the write has actually been fully committed to the leveldb backend? This way the throttling would happen automatically on the publisher side and the subscribers should keep up.
Currently it seems pretty much impossible to have reliable delivery at high speeds with leveldb active. (just to re-iterate - once leveldb is disabled the subscribers can happily keep up with the publishers so the bottleneck isn't the subscriber but vernemq itself)

It's either that or the read from leveldb is massively inefficient for some reason but then I don't how that could be fixed.

**Comment by dergraf** [comment]
Hello @chriswue
Thank you for raising the question.

I see your point regarding the back pressure, but this is not what you want for every case, especially in a messaging system that should decouple a publisher from the consumer.

That said, our current message store implementation can 'still' be heavily improved wrt. performance. It's actually quite low hanging and will be done as soon as we have time to address it. I think improving the message store performance is the way to go here instead of 're-coupling' publisher and consumer. I hope that makes sense to you.

**Comment by chriswue** [comment]
Well, it's not so much about coupling publishers and subscribers. Right now the bottleneck affects the subscribers while I'm arguing for the fact that the bottleneck should be affecting the publishers. After all - what good does it do you if you can ingest truck-loads of data but can't actually deliver it?

Going over the vernemq and eleveldb code a little bit it looks like vernemq is doing a blocking write call to leveldb - while the write itself is async on the filesystem level by default (i.e. once leveldb hands it over to the OS it will return). Not sure where the big discrepancy of write vs read comes from. But I have no clue about Erlang so my interpretation might be wrong.

**Comment by dergraf** [comment]
You have some valid points, maybe @larshesel has an opinion on that as well.

The way the message store is currently implemented is that for every QoS > 0 message VerneMQ delivers a message record (metadata + payload) as well as additional references for every matching subscriber are stored. Most of the time a message record and those references are written and immediately deleted if the receiving clients are online and consume the messages right away. This case could be heavily improved using an intermediate cache so we only go to leveldb if the messages aren't consumed within a given time window.

**Comment by larshesel** [comment]
I think the points are very good. In a way we have basically two options: improve performance by speeding up the reads (which are not only reads, but also involve deleting a reference to the message) or avoiding touching leveldb altogether.

For improving the performance we'd first have to recreate the scenario (this may or may not be easy) so we can set up some basic benchmarking - but it would be helpful to know what the rates look like and how many subscribers are involved.

On a side-note it might be interesting to know that we're working on replacing leveldb with rocksdb (in VerneMQ 2.0 or as an opt-in for 1.x) it would be interesting to know if rocksdb has the same kind of behaviour (or perhaps has other cases which could be problematic). @dergraf has been working on a branch for this over here: https://github.com/erlio/vernemq/pull/888. Note, that branch also has a completely different replication mechanism (SWC instead of Plumtree).

I think in any case we should at some point built the intermediate cache where we, for some usecases at least, can avoid touching the message store altogether.

**Comment by chriswue** [comment]
For me the problem already appears with a single publisher + single subscriber. MQTT broker specs:

- Ubuntu 18.04.01 LTS
- docker 17.12.1.-ce
- 16 GB RAM
- Intel i7-4790 @ 3.6GHz
- Samsung SSD 850 EVO 250GB

I can publish (from a different PC) around 7,000-8,000 messages per at 1kb payload but only receive ~2,000/sec. With leveldb disabled the subscriber can keep up with the publisher rate in the exact same setup.
Granted it's not the best SSD in terms of IOPS but `iostat -x 5` reports less than 5% utilization during the benchmark.

I've used the C# MQTTnet library for pub/sub clients.

**Comment by dergraf** [comment]
Well, as said before publisher and subscribers are decoupled. 
The LevelDB writes/deletes for QoS > 0 happen inside the subscriber queue so the LevelDB overhead won't punish your publisher (of course only as long as CPU/Memory isn't exhausted).

Regarding write/delete performance, the subscriber queue processes those messages sequentially, moreover the LevelDB writes/deletes are blocking. As a result a single subscriber won't be able to utilize parallel writes to LevelDB.

That said, we have never optimized VerneMQ for exactly this scenario. If you balance your messages over multiple subscribers you should see different performance results, as well as better SSD utilization.
