### ISSUE TITLE
Subscriber missing published messages from cluster

### ISSUE THREAD

**Issue by emgitingit** [vernemq/vernemq#919]
### Environment

- VerneMQ Version: 1.5
- OS: ubuntu 
- Erlang/OTP version (if building from source):

### Expected behavior

Subscribers should be able to receive the messages for the topic under heavy load.

### Actual behaviour

While running in production env and there is a lot of heavy load, sometimes the subscribers aren't getting the messages published. I do see the broker published it but nothing received by the subscriber. Unfortunately, I'm unable to reproduce locally or even on dev.  

I have 2 different mqtt clients one using paho-mqtt python and the other paho-mqtt golang and both of them didnt get the message at the time. 

Production isn't even getting a lot of messages too (< 10k each). and there are already 4 nodes in the cluster. Is there some configuration I'm missing?

**Comment by dergraf** [comment]
Hi there,

Could it be that VerneMQ is doing load shedding and therefore actively drops messages. More details about it here https://docs.vernemq.com/configuring-vernemq/options#load-shedding

You'd notice it in the logs as well as the metric `queue_message_drop` 

I hope this helps!

Enjoy your weekend.

**Comment by chriswue** [comment]
You subscribe with QoS 0 which explicitly means "I don't care wether or not I receive all messages". QoS 0 messages are not queued by default so if the broker drops it then it probably won't count against `queue_message_drop` since they were never in the queue. I thought there was a setting to instruct it to queue up QoS 0 messages as well but I can't find it right now.

**Comment by emgitingit** [comment]
> You subscribe with QoS 0 which explicitly means "I don't care whether or not I receive all messages". QoS 0 messages are not queued by default so if the broker drops it then it probably won't count against `queue_message_drop` since they were never in the queue. I thought there was a setting to instruct it to queue up QoS 0 messages as well but I can't find it right now.
> 
> Ultimately if you care about message delivery you should use at least QoS 1

yea but if its a stable connection qos =0 shouldnt be a problem. I have set the client to qos = 2 for now. I still saw that sometimes subscribers weren't getting the message so I incremented the max inflight messages to 50. 

thanks!

**Comment by emgitingit** [comment]
> Also are you seeing any errors in the logs?

No errors in the log and all brokers in the cluster looks like its busy doing stuff based on the logs. I did see some keepalive expired which might be because of the new mqtt specs but no other errors. 

thanks =)

**Comment by chriswue** [comment]
If you're overloading the subscribers then the stability of your connection doesn't matter - if they can't keep up then messages will be dropped. You said heavy load - not sure what means in your case but with the default vernemq config a single subscriber tops out at about 2000 messages/sec on our hardware (Samsung EVO 850 SSD, quad core i7, 16GB RAM)

Keepalive expired might indicate a problem because I think that will kill the session and the client may have to reconnect - have you logged any re-connect events in the clients?

**Comment by emgitingit** [comment]
thanks! its weird cause i did a client trace at the time and its still connected cause i see the pings. But at that time, it didnt receive the message. I havent seen it consistently so its hard to debug. Will keep an eye on it! thanks! closing for now.
