### ISSUE TITLE
Not able to authenticate using MySql

### ISSUE THREAD

**Issue by Dharmik8478** [vernemq/vernemq#975]
### Environment

- VerneMQ Version: 1.6.1
- OS: CentOS Linux release 7.5.1804 (Core)

### Expected behavior

- It should authenticate using MySql db.

### Actual behaviour

- In console.log getting error: can't authenticate client {[],<<"0810269c-1e92-4229-b33b-3d506ab9f7c61543128280729">>} due to invalid_credentials

I have done all the required configuration given [here](https://docs.vernemq.com/configuring-vernemq/db-auth) and here is my sql configurations:

- sity.auth_mysql.enabled = on
- vmq_diversity.mysql.host = localhost
- vmq_diversity.mysql.port = 3306
- vmq_diversity.mysql.user = user
- vmq_diversity.mysql.password = ******
- vmq_diversity.mysql.database = botodb

**Comment by larshesel** [comment]
Hi, since you get the above log this means some plugin is rejecting your client. Maybe you have other plugins enabled (`vmq_passwd` for example?) which reject the client before `vmq_diversity` is run? Check with `vmq-admin plugin show`. Also have you set `plugins.vmq_diversity = on` as per the docs?

If that is not the case enable the query log in MySQL and see that the query sent by `vmq_diversity` is actually sent and that it returns the expected data.
